### ISSUE TITLE
Unexpected character after line continuation character

### ISSUE THREAD

**Issue by Vancore** [k0rnh0li0/onlyfans-dl#10]
I am stuck, when I run the python script I get the following error message:

```
SyntaxError: unexpected character after line continuation character
>>> \onlyfans-dl.py acc-name token
  File "<stdin>", line 1
```

Can you help me out with this?

**Comment by MakotoYasuhiro** [comment]
If using windows, instead of launching Python, I just use "py onlyfans-dl.py <user> <access token>"

**Comment by Vancore** [comment]
Ahh you're right, it was an issue with windows ;). Another question, now that it is running it tells me:

```
Saving profile info...
Finding posts...
ERROR: 0 posts found.
```

I am logged in and also subscribed. What is the format of the user, the User name (full name) or the @u.... or just the u... ?

Thanks in advance @MakotoYasuhiro !

**Comment by Vancore** [comment]
I think I will open another issue, this one is done.
