### ISSUE TITLE
Keep getting "ERROR: Wrong user."

### ISSUE THREAD

**Issue by Yonilicious** [k0rnh0li0/onlyfans-dl#103]
Keep getting "ERROR: Wrong user." using any username profiles I'm subscribed to.

I'm certain I have everything in the configurations section set up correctly, am I doing something wrong?

**Comment by MrAutismo** [comment]
I can confim that :(

**Comment by Trible789** [comment]
You need to define the user id from the profile you want to download. Just look inside of one of the JSON Requests when you visit the profile.

**Comment by darkhaiass** [comment]
The user-id i get from the JSON requests is always the same and it keeps saying wrong user.

**Comment by Cyberace1985** [comment]
im 90% sure i have this right but its still failing

**Comment by SenpaiX00** [comment]
> im 90% sure i have this right but its still failing

I tested yesterday and everything works as it is supposed to. Are you sure you are correctly modifying the required values in the script?

**Comment by SecondThrow** [comment]
Try confirming that your user agent hasn't changed. I've noticed every few days I've been getting a minor bump in my Chrome version number. Updating the value fixed the issue for me.

**Comment by Yonilicious** [comment]
Yeah I think I had my user agent wrong this whole time. I smooth-brained it originally and only copied in the Firefox part of the String, not the entirety of it which contains multiple browsers.. *facepalm*

Couldn't find any .JSON files in the Network tab btw, but the XHR entries also contained the x-bc and user id.

Sorry for the user-error kerfuffle.. Thanks for this tool guys.
