### ISSUE TITLE
KeyError: 'canViewMedia'

### ISSUE THREAD

**Issue by Catralitos** [k0rnh0li0/onlyfans-dl#106]
Everything seems to be working and then:

Media already present will not be re-downloaded.
Saving profile info...
Finding photos... Found 1492 photos.
Finding videos... Found 173 videos.
Finding archived content... Found 2 archived posts.
Found 1667 posts. Downloading media...
Traceback (most recent call last):, Estimated Time left: 0:00:01, Estimated finish time: 02:42:37
  File "./onlyfans-dl.py", line 321, in <module>
    cur_count = download_posts(1, photo_posts, False)
  File "./onlyfans-dl.py", line 222, in download_posts
    if not post["canViewMedia"]:
KeyError: 'canViewMedia'

I don't know what's happening

**Comment by Damian77** [comment]
Hello,

Probably something has changed in response request from API, quick fix (without actually checking root cause):

`def download_posts(cur_count, posts, is_archived):
    for k, post in enumerate(posts, start=1):
        if "canViewMedia" not in post:
            continue
        if not post["canViewMedia"]:
            continue

        if "media" not in post:
            continue
        for media in post["media"]:
            if 'source' in media:
                download_media(media, is_archived)

        # adding some nice info in here for download stats
        timestats = calc_process_time(starttime, k, total_count)
        dwnld_stats = f"{cur_count}/{total_count} {round(((cur_count / total_count) * 100))}% " + \
                      "Time elapsed: %s, Estimated Time left: %s, Estimated finish time: %s" % timestats
        end = '\n' if cur_count == total_count else '\r'
        print(dwnld_stats, end=end)
        
        cur_count = cur_count + 1

    return cur_count`
