### ISSUE TITLE
Access Tokens Giving "Access Denied"

### ISSUE THREAD

**Issue by MakotoYasuhiro** [k0rnh0li0/onlyfans-dl#11]
Things were working fine for a week or two. Starting a couple days ago, anytime I attempted to run the script I'd get "ERROR: Access denied." after "Getting user auth info...".

Once this happens, my OnlyFans tab also gets automatically signed out, required me to sign back in.

Not sure if the API has changed or has been removed, but this script is currently unusable for me.

**Comment by PythonLimited** [comment]
Works fine here
Make sure to update the user-agent in the script to the one from your browser...

**Comment by MakotoYasuhiro** [comment]
Yep, I'm an idiot. Adding a script to automatically update my access token, completely forgot about having to update the user-agent. The errors going out made me think it was some sort of issue with my account authorization. No issues now with user-agent updated.
