### ISSUE TITLE
Download text as well?

### ISSUE THREAD

**Issue by blmatthews** [k0rnh0li0/onlyfans-dl#110]
Has any thought been given to saving the text in posts, messages, etc? I realize the primary purpose is images and videos (for which it works quite nicely!), but some posts have explanatory text, and others are all text (stories, etc.) that it would be nice to save.

**Comment by LeninZapata** [comment]
I think this idea is excellent, in addition to each download a .TXT is saved with the date of each update and the files I download, to control the TIMESTAMP range of the account, so for example one wants to download from a set date to a profile , only the TIMESTAMP is changed and ready, the file must recognize that it must download from that time forward.
