### ISSUE TITLE
The Ultimate Confusion

### ISSUE THREAD

**Issue by mansbeat121** [k0rnh0li0/onlyfans-dl#112]
So I'm very new to Python and I'm trying to figure this out. Every time I do what the guide says, I constantly get errors and none of the errors are in the issues so I'm not going to bother trying to post it because I'm sure it's Python and not the script. Can anyone create a more visual/specific tutorial? I really don't want to sound dumb, but I would really like to get this script working.

**Comment by demib72** [comment]
Even if you think the errors are specific to python, it still helps to post them.

**Comment by SenpaiX00** [comment]
Firstly, you should post the specific errors you are getting. Secondly,
raising an issue isn't a feature of Github that exists to help you learn
Python.

**Comment by SenpaiX00** [comment]
A more visual tutorial? It sounds like you are new to coding and
web technologies in general. You may not want to sound dumb, but you do.
