### ISSUE TITLE
ERROR: Wrong user. 

### ISSUE THREAD

**Issue by Amare728** [k0rnh0li0/onlyfans-dl#114]
Getting ERROR: Wrong user. 

I've made no changes to the script, and it used to function as expected.

![Capture](https://user-images.githubusercontent.com/93739945/140420258-3968deee-a600-4485-ad85-99e7e9c8633f.PNG)

**Comment by SecondThrow** [comment]
Make sure to re-check all the values you put into the script. OF can change your session cookie or x_bc value at any time. Also, double-check the user agent because Chrome sometimes will put out minor updates that bump up the browser number.

**Comment by Amare728** [comment]
That did it, did a browser update also, thanks
