### ISSUE TITLE
Wrong user? 

### ISSUE THREAD

**Issue by Greenonion32** [k0rnh0li0/onlyfans-dl#116]
I think i did everything right, but when i enter the username im looking for it just says Error: Wrong user. 
I already triple checked the username, and made sure there are no extra spaces. 

Is this my fault or is this a problem with OF?

**Comment by c1ockwork** [comment]
Getting this also.  Have verified the necessary variables.  Output is just:

Getting target profile info...
x

ERROR: Wrong user.

**Comment by Almostdivine** [comment]
Guys, just modify script at line 62: 

Before: "Cookie": "sess=" + SESS_COOKIE
After:  "Cookie": "csrf=xxxxxxxxx; fp=xxxxxxxxx; cookiesAccepted=true; auth_id=xxxxxx; sess=xxxxxxx; ref_src=https://accounts.google.com/; st=xxxxxxxx"

You can take value from "cookie" of Request Headers. Then you can use it again.
