### ISSUE TITLE
0 posts found

### ISSUE THREAD

**Issue by Vancore** [k0rnh0li0/onlyfans-dl#12]
Not sure what is wrong, I get:

```
Saving profile info...
Finding posts...
ERROR: 0 posts found.
```

I am not sure about the form of the user, I am using the u... format.

**Comment by MakotoYasuhiro** [comment]
If you were to want to download from @belledelphine, you'd use the Windows command
`py onlyfans-dl.py "belledelphine" "asdfzxcvqwer1234"`

I'd also check to make sure you have proper header information for your browser inserted into the script like described in the readme

**Comment by Vancore** [comment]
Works, thanks bro! :)
