### ISSUE TITLE
ERROR: Something went wrong. [A74FC255]

### ISSUE THREAD

**Issue by Pwnager12345** [k0rnh0li0/onlyfans-dl#121]
I keep getting this error. I have triple and quadruple checked the user_id, sess, user_agent, and x-bc but I keep getting the same result.

`Getting target profile info...
x

ERROR: Something went wrong. [A74FC255]`

I haven't updated in a while so I was using an older version of the script (7.4.1) and it worked perfectly until this morning when it just would not authorize. I tried to clone the latest repo and try again but I got this^ result. I think the Onlyfans devs changed something again. Or I'm just an idiot and not using it correctly. Who knows?

**Comment by god43** [comment]
nope i have the same issue.

**Comment by simont-org** [comment]
Same for me. I was able to download an entire profile at 1 PM (CET) and after that I always had the error. Moreover, as soon as I get the "smth wrong" error, I get logged out from OF if I was logged in the browser.

**Comment by Arundidoo** [comment]
also got the same issue, is this because we haven't set something up properly or is it an issue with the code?

**Comment by antzpantz** [comment]
It seems like something has changed again on OF's side.

**Comment by FungoPalumbo** [comment]
Same here. Is there any way to fix this?

**Comment by dumpbox76** [comment]
ERROR: Something went wrong. [A74FC255]

Yep, same problem here.

**Comment by Crimsoonhack** [comment]
Same here!

**Comment by mr-frump** [comment]
Hoping someone can figure this out. I was messing with it, but haven't had any luck.

**Comment by martonsz85** [comment]
Same problem here, and so far I haven't been able to figure out what the problem is.

**Comment by Th3K1n91** [comment]
#122

**Comment by k0rnh0li0** [comment]
I merged Th3K1n91's patch and it looks good to me. Are you guys still having issues?

**Comment by xPokerr** [comment]
> I merged Th3K1n91's patch and it looks good to me. Are you guys still having issues?

Now it's working 👍

**Comment by Pwnager12345** [comment]
Great! Working now 👍

**Comment by k0rnh0li0** [comment]
@Th3K1n91 I just wanted to say thanks for submitting that PR. I hadn't gotten a chance to look at this so I appreciate the effort brother
