### ISSUE TITLE
View the list of subscribed profiles

### ISSUE THREAD

**Issue by Pwnager12345** [k0rnh0li0/onlyfans-dl#123]
Is there a way to view the list of my subscribed profiles sorted by expiry/renew date? Like from DigitalCriminal's version where it prints the whole list of subscribed profiles and you chose the profile to download from that list?

I just want to be able to see the list of my subscribed to profiles so I can know which is going to expire the soonest. Onlyfans used to have that function to sort the lists but its gone now, don't know why.

**Comment by Th3K1n91** [comment]
#124

**Comment by Th3K1n91** [comment]
#126
