### ISSUE TITLE
ERROR: Please refresh the page

### ISSUE THREAD

**Issue by OmegaTangent** [k0rnh0li0/onlyfans-dl#127]
Getting this since today, I checked and double-checked everything in the script from cookie to auth id. Tried it with python -m and python -s and ./ so I don't know for sure what's going wrong. Thanks for the help!

**Comment by Th3K1n91** [comment]
Download latest commit and make sure you fill your auth in file auth.json.

The error "refresh the page" is because you setup a wrong user-agent.

**Comment by OmegaTangent** [comment]
Thanks, I now redownloaded the repo and filled everything in, now it works fine!
