### ISSUE TITLE
Error BB91C8D6

### ISSUE THREAD

**Issue by ImModex** [k0rnh0li0/onlyfans-dl#133]
Hey everyone, I just downloaded the latest patch since it hasn't been working for a bit but it still persists. The only thing my console says after entering the variables in auth.json is

ERROR: Something went wrong. [BB91C8D6]

Also I can't find the "x-bc" variable anywhere so that may be the problem?

**Comment by Stargatemunky** [comment]
if you're using firefox you need to enable raw data to see the x-bc value more clearly.

**Comment by ImModex** [comment]
> if you're using firefox you need to enable raw data to see the x-bc value more clearly.
> 
> There's a little tab in the bottom right where you can see the data.

That worked for me, thank you!
