### ISSUE TITLE
Access Denied

### ISSUE THREAD

**Issue by deakaii** [k0rnh0li0/onlyfans-dl#134]
Anyone getting this message today? Worked without issue last week, can manually access the intended profiles, is this a standalone issue or a larger change that was made?

**Comment by Th3K1n91** [comment]
Download latest commit and make sure you fill your auth details in auth.json

**Comment by deakaii** [comment]
Re-downloaded today, JSON is filled out, going to double check the appropriate values are in the variables, but so far that's what I did this AM

**Comment by tealsteam** [comment]
Hey all, been using this for a few months, latest release brings back Access Denied for me when filling the relevent information in the auth.json file

**Comment by deakaii** [comment]
So it's not just me...good to hear, but also bad to hear.
