### ISSUE TITLE
Naming convention configuration for downloads

### ISSUE THREAD

**Issue by spent38** [k0rnh0li0/onlyfans-dl#135]
Would it be possible to implement a way to configure the naming convention for files downloaded? I would love to be able to download all of the media and have the file names automatically prefixed with the date of the post (Ideally in year, month, day format).

**Comment by blmatthews** [comment]
That's the main reason I use Voldrix's fork. It saves things as YYYY-MM-DD_id.ext (plus I've modified my local copy to touch each file with its date.) However, k0rnh0li0 has done a bunch of work on his that I'd like to have, so I'm hoping someone mashes them together, or at some point I get time to do that (and add saving of text, which I'd still like.)
