### ISSUE TITLE
Value of 'new_files' needs to be reset to zero when multiple models are chosen

### ISSUE THREAD

**Issue by AnoCurly** [k0rnh0li0/onlyfans-dl#142]
The value `new_files` needs to be reset at the beginning of the `for M in SELECTED_MODELS:` loop, otherwise the print statement of each model will be:

_Downloaded x new files._

Where `x` is the total number of the files of all models. But I guess it is supposed to be the number of the files of the current model.

**Comment by jordon31** [comment]
https://github.com/jordon31/OF-SCR

try my updated script
