### ISSUE TITLE
ERROR: Access denied

### ISSUE THREAD

**Issue by ColtraneNadler** [k0rnh0li0/onlyfans-dl#144]
Getting ERROR: Access denied.
even though all the auth.json fields are correct, and then it logs me out of all active OF sessions

**Comment by maxc0** [comment]
I am having the same issue. It was working fine a few days ago though.

**Comment by liqdfire** [comment]
Double check your values in auth.json.

This error means that the signed header is being rejected. I was getting the same error because I had put my x-bc value in as my sess as well. Once I fixed my values the error went away.

**Comment by maxc0** [comment]
I quadruple checked it - that's not the issue. I think onlyfans has figured out how to deafeat the program because I get logged out of my onlyfans account every time I run the program.

**Comment by liqdfire** [comment]
> r

If you are getting logged out, then one of your settings is definitely not correct. I suspect it is your User Agent if you are getting logged out.

I downloaded the script from the master branch this morning and it is fully functional.

**Comment by theonlyfan2020** [comment]
Same thing hapenned here. Solved as @liqdfire said. It was the user agent, the broswer has been updated, so OF was dropping me. Update the config files with the new user-agent version and should work.

**Comment by maxc0** [comment]
Yall were right. It was the user-agent. Didn't think of updating it earlier. Thanks guys.
