### ISSUE TITLE
Browser not sending X-BC?

### ISSUE THREAD

**Issue by fttdgc** [k0rnh0li0/onlyfans-dl#145]
I've looked through a dozen different login attempts but cannot find a section entitled X-BC. Is there another name for it or does it not always get sent?

The options I have in the js's include

x-amz-cf-id
x-amz-cf-pop
x-cache
x-content-type-options
x-frame-options

Then when it gets into the cookie header area the various parts are

csrf=;
__stripe_mid=; 
cookiesAccepted=true; 
ref_src=; 
fp=; 
st=; 
sess=

**Comment by blmatthews** [comment]
x-bc is a request header. Look in requests of type xhr in Chrome or json in Firefox. The easiest place to look is probably stats-collect requests, as they're repeated periodically.

**Comment by fttdgc** [comment]
Perfect. Thanks!
