### ISSUE TITLE
Multiple errors

### ISSUE THREAD

**Issue by Ghadzoeux** [k0rnh0li0/onlyfans-dl#146]
I updated the code with the latest, changed all parameters accordingly but when I launch the script I get this :

Traceback (most recent call last):
  File "x:\pathonmyPC\onlyfans-dl-master\TJ.py", line 298, in <module>
    API_HEADER = create_auth()
  File "x:\pathonmyPC\onlyfans-dl-master\TJ.py", line 50, in create_auth
    with open("auth.json") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'auth.json'

**Comment by k0rnh0li0** [comment]
??? What is "TJ.py"?

**Comment by Ghadzoeux** [comment]
It's the original py file, I just renamed it, depending on the account I use it for. Can it be a problem ?

**Comment by k0rnh0li0** [comment]
Well, what other modifications have you made? If you moved the script out of the original directory, then it won't be able to find auth.json, which would cause this error

**Comment by Ghadzoeux** [comment]
The file is in the folder where others are too.

**Comment by Ghadzoeux** [comment]
There wasn't the auth.json in the folder. I put it back, my mistake. Anway, the issue's still here 
Traceback (most recent call last):
  File "E:\blabla\onlyfans-dl-master\onlyfans-dl.py", line 298, in <module>
    API_HEADER = create_auth()
  File "E:\blabla\onlyfans-dl-master\onlyfans-dl.py", line 51, in create_auth
    ljson = json.load(f)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 151946: character maps to <undefined>

**Comment by k0rnh0li0** [comment]
The issues you're having aren't issues with onlyfans-dl. Whatever changes you made, or problems with your local environment, are causing these issues. I recommend cloning a fresh copy of the repo and not changing it, just run the script and download the profiles you want

**Comment by Ghadzoeux** [comment]
I see my mistake now, I didn't realise you changed the way the files were working and that I only had to modify the auth.json and not the big .py file like it used to be.
Thanks for the help, it now works perfectly.

**Comment by bnsave100** [comment]
> I see my mistake now, I didn't realise you changed the way the files were working and that I only had to modify the auth.json and not the big .py file like it used to be. Thanks for the help, it now works perfectly.

close issue now haha

**Comment by LeninZapata** [comment]
I did a clean installation of Python 3.10 + installation requests + config JSON = It works correctly
