### ISSUE TITLE
Fomat name files - YYYY-MM-DD H:i:s

### ISSUE THREAD

**Issue by LeninZapata** [k0rnh0li0/onlyfans-dl#147]
Hello, could you add the function of filename variables, for example I would like to have the format:
`{user}-{date}-{time}-{ID}`

where

**user** = profile user
**date** = chosen format of date
**time** = chosen time format
**ID** = file id .....

could you add this feature? It is important for me to know the date of the file and the username.

---
PS: I tried the file and it works great, I had to use a VPN pointing to the USA so that it allows me to download the files since in my country "Ecuador" sometimes the images are not displayed within OF, but with a VPN it is solved everything :)

**Comment by Voldrix** [comment]
my fork does {user}/{date}_{id}.{ext} if you want to check it out.
