### ISSUE TITLE
ERROR: Access denied. ???

### ISSUE THREAD

**Issue by YoSoyAngi** [k0rnh0li0/onlyfans-dl#148]
When i open the file it says:

ERROR: Access denied.

**Comment by deakaii** [comment]
Go back and double check your auth.json

You've messed up somewhere,

"user-agent": "Mozill.....
"user-id": "123....
"sess": "jd8ejfn89....
"x-bc": "o945kpd....

**Comment by snarl817** [comment]
I'm having the same issue. Snarfed the values from the console and put them in the json file...well, BOTH json files. .profiles/default/auth.json AND .profiles/OnlyFans/default/auth.json. Tells me:
Auth (V1) Attempt 1/10
Something went wrong. [BB91C8D6]
Auth (V1) Attempt 2/10
Access denied.

**Comment by GizmoTheGreen** [comment]
also just getting access denied, refreshed all values and updated the script (previous version I used didn't have seperate auth file)

ERROR:ACCESS DENIED.

**Comment by davidtonzar** [comment]
It's working fine for me, it's downloding as of Jan 3rd. I've read the mentioned error is related to x-bc so make sure that value it's up to date. This may also help, there's a code to make a self generated x-bc on the digitalcriminal git https://github.com/DIGITALCRIMINAL/OnlyFans/issues/1780#issuecomment-997992837 so it may work genereting one and write it to auth.json file so then the script can use it. I have not tried that.

Btw I had error when script calling to open auth.json file not found and on Windows I was able to fixed it by adding this above line 50:
from os import path
