### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or director: 'auth.json'

### ISSUE THREAD

**Issue by drdown33** [k0rnh0li0/onlyfans-dl#152]
C:\Users\...>python C:\Users\...\Downloads\onlyfans-dl-master\onlyfans-dl.py nvalentine

~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~ I AM THE GREAT KORNHOLIO ~
~  ARE U THREATENING ME??  ~
~                          ~
~    COOMERS GUNNA COOM    ~
~    HACKERS GUNNA HACK    ~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Traceback (most recent call last):
  File "C:\Users\...\Downloads\onlyfans-dl-master\onlyfans-dl.py", line 306, in <module>
    API_HEADER = create_auth()
  File "C:\Users\...\Downloads\onlyfans-dl-master\onlyfans-dl.py", line 50, in create_auth
    with open("auth.json") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'auth.json'

I am getting this error. I saw that another user posted the error, but had messed around a bit with the install. This is a fresh install, I installed 3.10 and installed the request library and upgraded the request library. Auth.json is in the same folder as the python script. I'm not sure what else to do.

**Comment by david-017** [comment]
@drdown33 I had the same error. Make sure PS path is pointing to the location where you saved the script. Use cd command to change to the that directory.

So terminal has to start with
PS C:\your_path_to_script>

from there you write python.exe file path followed by a space and onlyfans-dl.py complete path and model name as you already did.

**Comment by fgtfv567** [comment]
> @drdown33 I had the same error. Make sure PS path is pointing to the location where you saved the script. Use cd command to change to the that directory.
> 
> So terminal has to start with PS C:\your_path_to_script>
> 
> from there you write python.exe file path followed by a space and onlyfans-dl.py complete path and model name as you already did.

How do you do this on windows? I'm having a difficult time following your instructions

**Comment by kusti420** [comment]
> > @drdown33 I had the same error. Make sure PS path is pointing to the location where you saved the script. Use cd command to change to the that directory.
> > 
> > So terminal has to start with PS C:\your_path_to_script>
> > 
> > from there you write python.exe file path followed by a space and onlyfans-dl.py complete path and model name as you already did.
> 
> How do you do this on windows? I'm having a difficult time following your instructions

same as you just said, cd into wherever you saved it and run it witb python
