### ISSUE TITLE
Script won't download more than 100 items at one time

### ISSUE THREAD

**Issue by Spamspamqqq** [k0rnh0li0/onlyfans-dl#153]
I'm looking to scrape from a user who has > 1000 items, but even though I've changed the POST_LIMIT to 1200, its still only downloading 100 items.

I tried the solution offered in [#92](https://github.com/k0rnh0li0/onlyfans-dl/issues/92), but given that the "if posts_num < 100" instances have been changed to "if posts_num < POST_LIMIT", it changed nothing in the output.

I checked down at the "# get all user posts" block, and POST_LIMIT has not been updated to 100.

It only ever calls out that it finds 50 photos and 50 videos, even if there are more of each on the profile, and on a couple of the profiles, it has downloaded much more than 50 photos or videos when it said it only downloaded 50, but when I try to run the scraper again, it doesn't download more.

I have changed nothing in the original script besides this constant, and am at a loss as to what to try next.  Any thoughts?

**Comment by FungoPalumbo** [comment]
Same here. I tried some work around but nothing worked

**Comment by Voldrix** [comment]
OF just changed the API posts per call limit to 50. Set the limit to 50 for the pagination to work.

**Comment by rewsdev** [comment]
I posted a fix for this and created a PR. #154
