### ISSUE TITLE
"No models subbed"

### ISSUE THREAD

**Issue by soyTorch** [k0rnh0li0/onlyfans-dl#155]
I put the user and the id of this user but it keeps giving me this error 
![image](https://user-images.githubusercontent.com/96847130/149820445-a7a214ed-c00e-495c-9bb5-34cc7bb4085d.png)

**Comment by IceTorch66** [comment]
![image](https://user-images.githubusercontent.com/96847130/149820498-5812ae4d-030d-43ee-8cfa-94acb9f1ecc7.png)

**Comment by david-017** [comment]
You are getting that error cos that's not how you call the script to start downloading a model. Your fix:

First remove what you wrote on the script values of Profile and Profile ID. Leave those empty as they were.

I'm gonna asume you put the variables values requested on file auth.json and make sure they are the current values the site gives you for your session.

To start downloading. On terminal:

Make sure PS path is pointing to the location where you saved the script. In your case it's desktop. If not, use cd command to change to the right directory. Looking at your screenshot that's correct already.

Then write path to your python exe. I have v3.10 so depending on your version it might be different , for me it's C:\Users\user_name\AppData\Programs\Python\Python310\python.exe
and right after that, separated by a space, write path to the scrypt .py so for you it would be C:\Users\34640\Desktop\onlyfans-dl-master\onlyfans-dl.py and now separated by a space write model name as it displayed on browser address bar. You're ready to go, press Enter. If you don't write model name scrypt lists your model subs and asigns numbers to them and ask you for the number you want to download.

So starting point for you is PS C:\Users\34640\Desktop\onlyfans-dl-master>
then if you have python 3.10 what you write should look like this:

C:\Users\34640\AppData\Programs\Python\Python310\python.exe C:\Users\34640\Desktop\onlyfans-dl-master\onlyfans-dl.py model_name

It will save all media to the script location under folder 'profiles'

**Comment by david-017** [comment]
@IceTorch66 
You are getting that error cos that's not how you call the script to start downloading a model. Your fix:

First remove what you wrote on the script values of Profile and Profile ID. Leave those empty as they were.

I'm gonna asume you put the variables values requested on file auth.json and make sure they are the current values the site gives you for your session.

To start downloading. On terminal:

Make sure PS path is pointing to the location where you saved the script. In your case it's desktop. If not, use cd command to change to the right directory. Looking at your screenshot that's correct already.

Then write path to your python exe. I have v3.10 so depending on your version it might be different , for me it's C:\Users\user_name\AppData\Programs\Python\Python310\python.exe
and right after that, separated by a space, write path to the scrypt .py so for you it would be C:\Users\34640\Desktop\onlyfans-dl-master\onlyfans-dl.py and now separated by a space write model name as it displayed on browser address bar. You're ready to go, press Enter. If you don't write model name scrypt lists your model subs and asigns numbers to them and ask you for the number you want to download.

So starting point for you is PS C:\Users\34640\Desktop\onlyfans-dl-master>
then if you have python 3.10 what you write should look like this:

C:\Users\34640\AppData\Programs\Python\Python310\python.exe C:\Users\34640\Desktop\onlyfans-dl-master\onlyfans-dl.py model_name

It will save all media to the script location under folder 'profiles'

**Comment by IceTorch66** [comment]
Okay, i have solutioned, thks, but now i have an other error xddd

"ERROR: Access denied."

What can i do? Thanks ans sorry for disturb

**Comment by BookReader101** [comment]
Certain types of browser addons that block connections to major CDNs and are used for local content delivery emulation will cause this type of issue, at least it did in my case. Something about it messes with login authorization, so the sess cookie doesn't get validated or something.
