### ISSUE TITLE
"ERROR: Access denied."

### ISSUE THREAD

**Issue by MickMod** [k0rnh0li0/onlyfans-dl#158]
Whenever I try to run the script I just get the error "ERROR: Access denied.".
If I configured the auth.json file wrong, let me know.

For "user-agent" I added the IP I got from IPChicken
"user-id" is 9 numbers
"sess" is 26 characters, letters and numbers
"x-bc" is 40 characters, letters and numbers

I got all but the first one from where the readme described, but I could have misunderstood what is meant by "user-agent".

Any help with fixing this is highly appreciated.

**Comment by MickMod** [comment]
I forgot to mention that I log in using my Google account, so that could also be what is causing the issue.

**Comment by LeninZapata** [comment]
It has presented me with the same error but in my case it was that the session ended quickly, also that it could not find the parameter "x-bc" after minutes they began to appear and it worked. Possibly OF is trying to do things to avoid filtering what we do.

**Comment by MickMod** [comment]
> 

How would you fix the session ending quickly issue? I just tried filling in the values as quickly as i could, while switching between pages on OF to keep the session going, but still got the same error. x-bc is available though.

**Comment by LeninZapata** [comment]
It did it by itself, after logging in like 3 times it stopped the logout behavior.

**Comment by MickMod** [comment]
So you logged in on your browser, got the values for the auth.json file, then just kept trying to run the script until it worked? Or did you do something else? I apologize if I'm asking a lot of questions, but I tried logging in, got the values, then the script, and it didn't work then either, so maybe I'm doing something wrong.

**Comment by LeninZapata** [comment]
every time the session is closed you have to update the auth.json again, I did this for 4 times until it worked

**Comment by MickMod** [comment]
I just figured it out, the "user-agent" in the auth.json file isn't your IP as it seemed by pointing to ipchicken, but it's actually the "Browser:" part. For example mine is "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:96.0) Gecko/20100101 Firefox/96.0".
Adding that to my auth.json file instead of my IP as I originally did, based off the site the guide points to, fixed my issue.
For the dev, thank you very much for making this, but clarifying what you mean by "user-agent" in the guide could be very helpful for people like me who don't know that much about programming.

**Comment by blmatthews** [comment]
The user-agent is also sent with each request as the value of the User-Agent header. Being getting the other things also requires looking at request headers, I'd suggest changing the procedure to get the user-agent from the headers. It should result in the same thing, but is one less place to look and ensures that the same value is being used as is being sent to OF.

**Comment by fgtfv567** [comment]
> t

OMFG You fixed it for me too, thank you so much
