### ISSUE TITLE
Crash without Error

### ISSUE THREAD

**Issue by Bcarr91** [k0rnh0li0/onlyfans-dl#159]
The app will crash randomly with no apparent errors; no matter the option I pick when selecting the models to download from. Every once in a while, a single model will download if I pick them individually, but more times than not it crashes out without warning. I just downloaded and setup my auth.json today. It sees the people I follow, it just keeps crashing.

**Comment by scopion1745** [comment]
I had similar problems. I swapped the "Cookie-Data" from Chrome to Firefox and it worked again

**Comment by BeachNL** [comment]
> I had similar problems. I swapped the "Cookie-Data" from Chrome to Firefox and it worked again

How?
