### ISSUE TITLE
No such file or directory: 'auth.json'

### ISSUE THREAD

**Issue by BeachNL** [k0rnh0li0/onlyfans-dl#161]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~ I AM THE GREAT KORNHOLIO ~
~  ARE U THREATENING ME??  ~
~                          ~
~    COOMERS GUNNA COOM    ~
~    HACKERS GUNNA HACK    ~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Traceback (most recent call last):
  File "D:\Downloads\Tools\onlyfans-dl\onlyfans-dl.py", line 345, in <module>
    API_HEADER = create_auth()
  File "D:\Downloads\Tools\onlyfans-dl\onlyfans-dl.py", line 50, in create_auth
    with open("auth.json") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'auth.json'
PS C:\Users\Beachy> cd D:\Downloads\Tools\onlyfans-dl
PS D:\Downloads\Tools\onlyfans-dl> python D:\Downloads\Tools\onlyfans-dl\onlyfans-dl.py bratprincessava

**Comment by CoinSearchr** [comment]
Did you download the entire repo? You have to have the auth.json file created and filled with the correct variables for the script to work

**Comment by KharonStyx** [comment]
I have this same issue running it as a cron job. It was copied in full from my machine (working) to the server. The files and directories are there the same as the repo. 
I get the below:

 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~ I AM THE GREAT KORNHOLIO ~
~  ARE U THREATENING ME??  ~
~                          ~
~    COOMERS GUNNA COOM    ~
~    HACKERS GUNNA HACK    ~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Traceback (most recent call last):
  File "./onlyfans-dl.py", line 354, in <module>
    API_HEADER = create_auth()
  File "./onlyfans-dl.py", line 50, in create_auth
    with open("auth.json") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'auth.json'

**Comment by blmatthews** [comment]
cron is a different environment in many ways from a login shell, so it's not terribly surprising that it works in a login shell and not from cron. I'd suggest adding `print('cwd:', os.getcwd(), file=sys.stderr)` before line 50 (before the `with open("auth.json") as f:` line). That should tell you the current directory, which is where the script is looking for auth.json. Move or copy auth.json there.

Alternately, add a `os.chdir('<path>')` near the top of the script (like after line 20), where \<path\> is where you want it to find auth.json and to save anything it downloads.

Another possibility would be to add `cd '<path>'; ` before the command in your crontab file. cron will still need to find the script though, so you may need to add the full path to the script as well.

**Comment by KharonStyx** [comment]
The 'cd "<path>; ./onlyfans-dl.py all' worked. The others never changed the outcome of the error above, But at least we have a workaround for now. 
Thank you @blmatthews 
Hopefully an easier fix can be implemented into the script itself.
