### ISSUE TITLE
Only Shows 100 Models

### ISSUE THREAD

**Issue by Nile42069** [k0rnh0li0/onlyfans-dl#166]
I follow over 300 creators and can only choose from the first 100. Any way to increase from 100?

**Comment by Nile42069** [comment]
I found an inconvenient work around. added this below line 163. Still only shows 100 results. So if I want to see the next 100, I'd change it to "offset": "199,
        "offset": "99",
        "type": "active",
        "sort": "desc",
        "field": "expire_date",

So if I want to see the next 100, I'd change it to "offset": "199,

Still if anyone can find a way for it to make a full list... I'd be psyched.

**Comment by Nile42069** [comment]
Made up new way... 
make list in onlyfans of profiles you want to dl then change line 170 to 
    return api_request("/lists/111111111/users", getparams=params).json()
The 1's I put will be where you put the list ID which you can get from the browser console.

**Comment by LeninZapata** [comment]
Hello, I have the same problem, I have put a higher number but I have an error, how can I show more than 100 subscriptions?


![image](https://user-images.githubusercontent.com/42600954/173123249-c1261777-19d8-4d97-868a-89a07ee4993c.png)

![image](https://user-images.githubusercontent.com/42600954/173123410-67e81bdb-a946-47ed-aeb0-356f13d91ea0.png)

**Comment by djmarioka** [comment]
Hi,

I'm having the same issue, I have 120 subscriptions aproximately, and it only shows 100, not everything.

Could you fix it?.

Thanks.

**Comment by menifesto123** [comment]
Has anyone found an update for this?

Thanks!

**Comment by jordon31** [comment]
https://github.com/jordon31/OF-SCR

try my updated script
