### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by Onigash** [k0rnh0li0/onlyfans-dl#167]
i run ./onlyfans-dl.py it opens then crashes

**Comment by trinaldi** [comment]
No error messages, nothing?

**Comment by Onigash** [comment]
I download the file double click onlyfans-dl.py it opens for a split sec then just closes

**Comment by LulzRose** [comment]
> I download the file double click onlyfans-dl.py it opens for a split sec then just closes

It is a python file, it must be run from CMD or terminal, follow the usage instructions on the readme.

**Comment by Jekotia** [comment]
Please check my linked response to another similar issue. It is likely that the program is not crashing, but instead this is user error originating from a lack of familiarity with how running a script works (:

https://github.com/k0rnh0li0/onlyfans-dl/issues/175#issuecomment-1109523714
