### ISSUE TITLE
Access Denied

### ISSUE THREAD

**Issue by shastan324** [k0rnh0li0/onlyfans-dl#169]
I have been able to use this in the past running vscode with a virtual python environment I set up just for this.  I opened it up today and updated the user-agent, user-id, sess, and x-bc but when I hit run it throws an access denied error instead of pulling up the list of subscribed accounts.

Edit: Still having issue with Firefox.  However I updated the auth.json to my chrome information and it is working.

**Comment by mannfranz** [comment]
same. thx for the workaround using chrome info

**Comment by agentlemonz** [comment]
Having same access denied issues when program first loads then crashes soon after, trying it with chrome info

**Comment by kusti420** [comment]
access denied even with chrome info

**Comment by blmatthews** [comment]
I just tried it. I had to update my info (I think Google installed a new version of Chrome since I last used the script), but once I did that it worked fine.

**Comment by kusti420** [comment]
> I just tried it. I had to update my info (I think Google installed a new version of Chrome since I last used the script), but once I did that it worked fine.

i tried everything, just using different user agent from chrome, updating sess-id from chrome. aint recieving json files on chrome, cant get x-bc on chrome from anywhere, had to use the old, one, used every combination of those, doesnt work, idk whats causing it

**Comment by blmatthews** [comment]
Are you mixing data from different browsers? That definitely won't work. Get all the values from a single browser while logged in to OF. In the network tab of the developer tools look for a stats-collect request then look at the request headers. Everything you need is in there.

**Comment by kusti420** [comment]
> Are you mixing data from different browsers? That definitely won't work. Get all the values from a single browser while logged in to OF. In the network tab of the developer tools look for a stats-collect request then look at the request headers. Everything you need is in there.

the point is that i tried getting all info from one browser from the same session at once, and it didnt work so i tried few different things. but nvm didnt see any stats-collect requests but request headers had x-bc, that fixed it

**Comment by kusti420** [comment]
stopped working again
