### ISSUE TITLE
KeyError for User-Agent

### ISSUE THREAD

**Issue by cfoote7** [k0rnh0li0/onlyfans-dl#171]
I'm getting the following error when I try to use this tool

Traceback (most recent call last):
  File "C:\Users\Chris Foote\onlyfans-dl-master\onlyfans-dl.py", line 345, in <module>
    API_HEADER = create_auth()
  File "C:\Users\Chris Foote\onlyfans-dl-master\onlyfans-dl.py", line 54, in create_auth
    "User-Agent": ljson["Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:99.0) Gecko/20100101 Firefox/99.0"],
KeyError: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:99.0) Gecko/20100101 Firefox/99.0'

anyone else run into this and know a solution?

**Comment by SnugglinBunny** [comment]
in your auth file the user agent line should be like this:
"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:99.0) Gecko/20100101 Firefox/99.0",

so remove ljson[ and the bracket at the end
