### ISSUE TITLE
Not finding/grabbing all videos

### ISSUE THREAD

**Issue by pth0rn** [k0rnh0li0/onlyfans-dl#174]
```
Finding photos... Found 14 photos.
Finding videos... Found 50 videos.
Finding archived content... Found 0 archived posts.
Found 64 posts. Downloading media...
```

However the profile has 175 photos and 101 videos

And it only downloaded 52 videos

**Comment by simonrule** [comment]
its said it downloaded the correct amount of the content on the profile but some of the files is missing

**Comment by nabob67** [comment]
in onlyfans-dl.py 
replace 
POST_LIMIT = 100 
by 
POST_LIMIT = 50

**Comment by lazyboy1729** [comment]
> in onlyfans-dl.py replace POST_LIMIT = 100 by POST_LIMIT = 50

In my case also same problem, tried with limit 50 then also no fix :-(

**Comment by gdprdatasubect** [comment]
Got the same issue, tried different limits (50, 20, 200), same problem.
Artist-page: 135 Photos, 99 Videos.
dl: 54 photos, 49 Vids

How do i debug this problem further?

**Comment by josegutierro** [comment]
same here

**Comment by jordon31** [comment]
https://github.com/jordon31/OF-SCR

try my updated script
