### ISSUE TITLE
Subdirectory for Messages/Paid

### ISSUE THREAD

**Issue by hirezz** [k0rnh0li0/onlyfans-dl#176]
Everything is scraped correctly except the videos I purchased are not grabbed while downloading the profile.

Is there anyway to set that to look at messages and scrape them as well?

**Comment by andrewfree** [comment]
> Everything is scraped correctly except the videos I purchased are not grabbed while downloading the profile.
> 
> Is there anyway to set that to look at messages and scrape them as well?

Do you see paid content that was on the main page but just not ones from messages?

**Comment by UltraUser6141** [comment]
Same thing on Messages not being scraped. Most of my purchased content is in messages, and this content isn't getting grabbed. Assume an update is needed to do this unless I'm missing something?

**Comment by Escopy88** [comment]
Yea I'm having the same issues. Not downloading anything from the messages
