### ISSUE TITLE
Authorization fails

### ISSUE THREAD

**Issue by Suppen8** [k0rnh0li0/onlyfans-dl#178]
Does anyone else have problems with authorization?

For me I can't use the script anymore since like a week.

I am getting "Access denied".

Previously it worked, so I am sure I am setting it up correctly. Everything in thje auth.json is freshly updated.

Anyone else have the same problems?

**Comment by kusti420** [comment]
> Does anyone else have problems with authorization?
> 
> For me I can't use the script anymore since like a week.
> 
> I am getting "Access denied".
> 
> Previously it worked, so I am sure I am setting it up correctly. Everything in thje auth.json is freshly updated.
> 
> Anyone else have the same problems?

yeah it randomly stopped working for me as well

**Comment by kusti420** [comment]
still not fixed, pls help

**Comment by blmatthews** [comment]
I just tried it, and after updating my info (from Chrome), it worked fine. Is it maybe some specific profile you follow? Maybe try some profiles you follow one at a time?

**Comment by kusti420** [comment]
> I just tried it, and after updating my info (from Chrome), it worked fine. Is it maybe some specific profile you follow? Maybe try some profiles you follow one at a time?

nah it just doesnt work, always says access denied

**Comment by kusti420** [comment]
got it working earlier and now it stopped working again

**Comment by Suppen8** [comment]
@kusti420 I noticed it stopped working for me if I logged out in the browser.
Try logging in, grab the information for auth.json and then try starting the script. It should work.
Now important! Don't log out in the browser. Just close it or smth. It seems the session gets deleted as soon as you log out and OF doesn't recognize it as valid anymore if you start the script. So try it without logging out

**Comment by kusti420** [comment]
@Suppen8 and the thing is that when you inspect element it also wants to log you out. So i guess you have to open that before and then refresh for a new session? And it still logs you out after some time it seems
