### ISSUE TITLE
Problems with the program

### ISSUE THREAD

**Issue by Hecatom** [k0rnh0li0/onlyfans-dl#187]
When trying to download the new photos and videos from the site, it only downloads files that have 110kb of size that are I pressume, just empty files.
And after logging on the site to see if there could be something on the site that could be causing those files to download like that, now it says ERROR: Access Denied when trying to run the program

**Comment by ewhgae457yaefgae4** [comment]
Hey dude,

Made an updated version that should fix this error. anonfiles com/d379Fe06y3/onlyfansdownloader_exe
