### ISSUE TITLE
Python Script Immediately closes upon opening

### ISSUE THREAD

**Issue by williamck123** [k0rnh0li0/onlyfans-dl#190]
it opens, and within a second closes. Any help?

**Comment by omencs** [comment]
Same pls help :(

**Comment by Escopy88** [comment]
I was having this problem as well. Make sure all the variables in auth.json is correct. Also make sure the pip install requests are loaded using this: python -m pip install requests

**Comment by ownzies** [comment]
> Same pls help :(

>it opens, and within a second closes. Any help?

If youre still having this issue and everything in auth.json is correct, and you have installed all the python requests, try this. 

Open the folder that your onlyfans-dl directory is in.. Create a text document in this folder. Copy and paste this code into the text document.

`echo on


python onlyfans-dl.py
`

Click "Save As" and change the "File Type" to "All Files", then name it something like "Launch.bat". Anything works, but make sure you put ".bat" at the end to turn it into a batch file. 

It should work now. Alternatively, you can just open CMD, CD to your directory, and execute "python onlyfans-dl.py". But creating a batch script is much easier if youre doing this more than once. 

For some reason, running the python file directly did not work for me, so this is how i solved it.
