### ISSUE TITLE
Cant get the "user-id" and x-bc Variable

### ISSUE THREAD

**Issue by Herobr1ne** [k0rnh0li0/onlyfans-dl#192]
Hey, tryed with Chrome and Firefox but cant get the right variable.
![raw](https://user-images.githubusercontent.com/33431587/185189104-07f5c91f-78a6-439c-80b7-81c94c950e81.png)

**Comment by Herobr1ne** [comment]
or is the authid the "user-id"? And where is the x-bc

**Comment by blmatthews** [comment]
Not all requests have all the things. Click on Fetch/XHR at the top to narrow it down to just xhr requests, then select one of those. They seem to always have all the required headers/cookies.

**Comment by Herobr1ne** [comment]
Thank you so much <3 Works great

**Comment by hyoretsu** [comment]
> Not all requests have all the things. Click on Fetch/XHR at the top to narrow it down to just xhr requests, then select one of those. They seem to always have all the required headers/cookies.

@k0rnh0li0 This should be included in instructions.
