### ISSUE TITLE
did not work in any way, the result is always : access denied

### ISSUE THREAD

**Issue by TheHans58** [k0rnh0li0/onlyfans-dl#195]
I tried many times in chrome and firefox, no matter what I do, I always get an acces denied error
![image](https://user-images.githubusercontent.com/68406822/187471557-0ffd101f-cfcf-4f14-8e14-af3680a56b0a.png)

**Comment by JunyiLi0804** [comment]
same issue

**Comment by blmatthews** [comment]
Just tried it, got Access denied, updated all the parameters (User Agent, etc), and now it works fine. I'd suggest verifying all the parameters.

**Comment by HashCookie** [comment]
Which is user-id
