### ISSUE TITLE
Processing files slows significantly after 100 files.

### ISSUE THREAD

**Issue by Speaker4TheD3ad** [k0rnh0li0/onlyfans-dl#198]
Hey I am seeing an issue where the processing of files slows significantly after 100 files or so are processed. E.g. account has ~800 video on it and I have downloaded ~60% of them. If I cancel and restart the download the processing of even detecting the video not even downloading gets slower and slower per file to the point it takes minutes to process one file. I have tried changing the POST_LIMIT value higher and lower but the result is the same.

Let me know if I can provide any more detail if this is confusing.

**Comment by Loquendo13** [comment]
I have the same problem, each time that a photo is donwloaded the estimated time increases
