### ISSUE TITLE
Getting Stuck at this Screen

### ISSUE THREAD

**Issue by electrifying84** [k0rnh0li0/onlyfans-dl#202]
![2022-10-16 13_27_34-Window](https://user-images.githubusercontent.com/114617753/196032784-a492d264-8dc3-4f9d-8a06-68e88dd3dcd3.png)

It worked like a Charm was good i mean if a model got 3000 pictures it sometimes only found 800 or so.. but the Vids where all downloaded... but now from one day to another it stopped.. i updatet pip already but still same it opens stays like this and doesnt retrieves models anymore.. i checked Cookie Sess Xbc and User Id.. all fine .. i logged out and logged back in again on the site and put in the new infos but still same.. anyone else experience this?

**Comment by jordon31** [comment]
https://github.com/jordon31/OF-SCR

try my updated script
