### ISSUE TITLE
Access Denied

### ISSUE THREAD

**Issue by woodchiprick** [k0rnh0li0/onlyfans-dl#203]
Seen some other issues with similar issues on the thread. Problem is I get a ERROR: Access Denied every time I try and run it. I've verified credentials and if I put false ones in it will return that the values are wrong. Also notice that it signs me out from only Fans every time I run and it fails. Tried on Firefox and chromium-based browsers and with VPN's but still no luck. IDK if a patch is needed but any help is appreciated

**Comment by DasKINIJI** [comment]
I had the same problems but it worked for me with the Tor browser

**Comment by SpagetthiMonster** [comment]
I also have the exact same error... Using chrome browser, validated the credentials multiple times, and it immediately sends "Access denied"

Is there a different browser where I can avoid this issue?

Also, I've tried adding the values from the other fields in the cookie to the auth.json dict, it hadn't had any effect...

Any help would be greatly appreciated

Thanks!

**Comment by unknown81311** [comment]
```
C:\Users\unknown\Downloads\o-dl-master>python -m pip install requests
Requirement already satisfied: requests in c:\users\unknown\appdata\local\programs\python\python311\lib\site-packages (2.28.2)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\unknown\appdata\local\programs\python\python311\lib\site-packages (from requests) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in c:\users\unknown\appdata\local\programs\python\python311\lib\site-packages (from requests) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\unknown\appdata\local\programs\python\python311\lib\site-packages (from requests) (1.26.15)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\unknown\appdata\local\programs\python\python311\lib\site-packages (from requests) (2022.12.7)

C:\Users\unknown\Downloads\o-dl-master>python onlyfans-dl.py

~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~ I AM THE GREAT KORNHOLIO ~
~  ARE U THREATENING ME??  ~
~                          ~
~    COOMERS GUNNA COOM    ~
~    HACKERS GUNNA HACK    ~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~

x

ERROR: Access denied.```

all of my credentials are identical to what they are on my browser.

**Comment by brakheart** [comment]
This problem still persists. Any help?
![image](https://github.com/k0rnh0li0/onlyfans-dl/assets/26739575/c35a4828-c875-4754-a41b-a6e1c6bae489)

**Comment by WizGery** [comment]
After some tests I have a hypothesis, in my case when it happens to me that is because I have been downloading many profiles in a row. So onlyfans temporarily "blocks" me from the script requests when using the "auth.json" with the chrome data. But if you fill the "auth.json" with the firefox data, which changes the "user-agent", "sess" and "x-bc". The script works again without problems. Try it and tell me if it works for you

**Comment by jordon31** [comment]
> After some tests I have a hypothesis, in my case when it happens to me that is because I have been downloading many profiles in a row. So onlyfans temporarily "blocks" me from the script requests when using the "auth.json" with the chrome data. But if you fill the "auth.json" with the firefox data, which changes the "user-agent", "sess" and "x-bc". The script works again without problems. Try it and tell me if it works for you

my script its best 

https://github.com/jordon31/OF-SCR
