### ISSUE TITLE
I have a question and request an answer

### ISSUE THREAD

**Issue by NoPatience7** [k0rnh0li0/onlyfans-dl#205]
Traceback (most recent call last):
  File "E:\onlyfans-dl-master\onlyfans-dl.py", line 345, in <module>
    API_HEADER = create_auth()
                
  File "E:\onlyfans-dl-master\onlyfans-dl.py", line 50, in create_auth
    with open("auth.json") as f:
       
FileNotFoundError: [Errno 2] No such file or directory: 'auth.json'

What is the problem?

**Comment by NoPatience7** [comment]
When I reinstalled python
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
I am a rookie, please expert adviceO(∩_∩)O

**Comment by KharonStyx** [comment]
#161 and a few others are saying the same thing. But no response in regards to this. looks like no one is actively looking at the issues...

**Comment by blmatthews** [comment]
I made some suggestions on #161, try those. Without knowing your exact environment it's not possible to offer an exact solution, but my suggestions might get you closer.

**Comment by jordon31** [comment]
https://github.com/jordon31/OF-SCR

try my updated script
