### ISSUE TITLE
Indentation Error: Unexpected Indent... What does this mean and how do I fix this? 

### ISSUE THREAD

**Issue by MarlinKano** [k0rnh0li0/onlyfans-dl#212]
I made it far, but as I copy and paste "onlyfans-dl.py" code into python it gives me an error: 

Indentation Error: Unexpected Indent this error is after many lines of the code. 

What exactly does this mean and how do I fix this? 

<img width="1440" alt="Screen Shot 2023-01-07 at 6 32 04 PM" src="https://user-images.githubusercontent.com/122184785/211174048-e1b7ad1f-8dfc-4ee6-9935-3ae616d4d71c.png">

**Comment by user7590831** [comment]
After pasting the code it probably got formatted automatically. I'd suggest you to clone the repo / download the file.
