### ISSUE TITLE
A Fix for anyone whos python script is instantly closing. Useful for those who do not really know what theyre doing with py and cmd.

### ISSUE THREAD

**Issue by ownzies** [k0rnh0li0/onlyfans-dl#213]
First, check that everything in auth.json is correct, and that you have installed all the python requests, this is documented in the instructions. If everything is correct and it still will not work, try this. 

Open the folder that your onlyfans-dl directory is in.. Create a text document in this folder. Copy and paste this code into the text document.

`echo on

python onlyfans-dl.py
`

Click "Save As" and change the "File Type" to "All Files", then name it something like "Launch.bat". Anything works, but make sure you put ".bat" at the end to turn it into a batch file.

It should work now. Alternatively, you can just open CMD, CD to your directory, and execute "python onlyfans-dl.py". But creating a batch script is much easier if youre doing this more than once.

For some reason, running the python file directly did not work for me, so this is how i solved it.

**Comment by KharonStyx** [comment]
Any idea how to fix the #161 issue that is related to automating this? seems scripts on linux throw out an error for the auth file even though the permissions etc are all correct... same goes for Windows but works fine when using the same script manually.

**Comment by Giftedbryan** [comment]
This doesn't work. it still crashes, I've used the program before and it worked fine then, but the launcher.bat file does nothing. In fact, it closes itself even faster now
