### ISSUE TITLE
ERROR: Access denied when running python script

### ISSUE THREAD

**Issue by yayayeet69** [k0rnh0li0/onlyfans-dl#216]
Getting the following error when running the script.

![Screenshot_20230122_214006](https://user-images.githubusercontent.com/90543997/213911664-f940e0c4-5ea5-4ada-8eac-3022f759cbbe.png)

I tried updating the auth,json file in case the details for my account changed for whatever reason, but this still occurs.

The script was working a few days ago.

**Comment by rot2301** [comment]
Had the same Issue when using Chrome, tried Firefox and it worked. Maybe that'll work for you aswell
