### ISSUE TITLE
x-bc and user-id cannot be found with instructions provided.

### ISSUE THREAD

**Issue by jadenquinn** [k0rnh0li0/onlyfans-dl#219]
I am unable to find these values with the instructions provided in the readme. Help?

**Comment by blmatthews** [comment]
Not all requests have all things, so if you don't find something in one request, try another. Also, don't look in the General section in the headers, scroll down to the Request headers. For, me right now, everything is in the request starting `list?`.

**Comment by jadenquinn** [comment]
> Not all requests have all things, so if you don't find something in one request, try another. Also, don't look in the General section in the headers, scroll down to the Request headers. For, me right now, everything is in the request starting `list?`.

I literally don't understand any of this... I'm not a dev.

**Comment by jadenquinn** [comment]
However, I was able to cross reference what these things mean with a site that I use for OnlyFans stuff too, but now I'm getting this: 
jaden@UltraYummyBlade ~ % cd '/Users/j/Downloads/onlyfans-dl-master/' && '/usr/local/bin/python3'  '/Users/j/Downloads/onlyfans-dl-master/onlyfans-dl.py'  && echo Exit status: $? && exit 1
Traceback (most recent call last):
  File "/Users/j/Downloads/onlyfans-dl-master/onlyfans-dl.py", line 16, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
jaden@UltraYummyBlade onlyfans-dl-master % cd '/Users/j/Downloads/onlyfans-dl-master/' && '/usr/local/bin/python3'  '/Users/j/Downloads/onlyfans-dl-master/onlyfans-dl.py'  && echo Exit status: $? && exit 1
Traceback (most recent call last):
  File "/Users/j/Downloads/onlyfans-dl-master/onlyfans-dl.py", line 16, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
jaden@UltraYummyBlade onlyfans-dl-master %

**Comment by jordon31** [comment]
https://github.com/jordon31/OF-SCR

try my updated script

**Comment by jadenquinn** [comment]
> https://github.com/jordon31/OF-SCR
> 
> 
> 
> try my updated script

Yours is even more faulty. Can't see anything in the video. I got a different script working that's just an updated version of this repo.

**Comment by jordon31** [comment]
> > https://github.com/jordon31/OF-SCR
> > Prova il mio script aggiornato
> 
> Il tuo è ancora più difettoso. Non riesco a vedere nulla nel video. Ho ottenuto uno script diverso funzionante che è solo una versione aggiornata di questo repository.

where do you see it bad? I download all the videos and works

**Comment by Loquendo13** [comment]
Go to your web broser, open the onlyfans, press ctrl + shift + i, click in network, press ctrl + r, in the search bar write the word "hint", in this file you will find all the 4 variables that you need in the response headers

**Comment by ericjs** [comment]
I find everything else but I find no trace of an "x-bc" header. I looked in hints and many other JSON type requests.

**Comment by ericjs** [comment]
Nevermind...it was in a request header. I mistakenly thought it only made sense to look in the response headers.
