### ISSUE TITLE
Error in lines 354, in <module> API_HEADER = create_auth() and in line 54, in create_auth "User-Agent":

### ISSUE THREAD

**Issue by HitoSantos** [k0rnh0li0/onlyfans-dl#224]
I'm getting the errors below when I try to run the script:

(1)
line 354, in <module>
    API_HEADER = create_auth()

  - What should I change in here?

(2)
line 54, in create_auth
    "User-Agent": ljson[""],

- I put the user-agent info for my browser in between the "" but it still doesn't work.

Any ideas?

**Comment by HitoSantos** [comment]
> ![image](https://user-images.githubusercontent.com/94505651/231046116-2e9a7b56-fc0f-4ab0-b79b-ee61be5eb949.png)
> 
> Put this

Hey, thanks for the help.

I tried it and it still doesn't work. I use a Mac so my User-agent is

**Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36**

- Even when I try this, I still get the errors:

Traceback (most recent call last):
  File "/Users/Me/Desktop/onlyfans-dl/onlyfans-dl.py", line 354, in <module>
    API_HEADER = create_auth()
                 ^^^^^^^^^^^^^
  File "/Users/Me/Desktop/onlyfans-dl/onlyfans-dl.py", line 54, in create_auth
    "User-Agent": ljson ["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36"],
                  ~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36'

**Comment by jordon31** [comment]
https://github.com/jordon31/OF-SCR 

try my updated script

**Comment by HitoSantos** [comment]
Thank you, Jordon!

Your script is perfect and so much simpler to execute. It worked like a breeze!
Thanks a lot!

**Comment by lilfmdude** [comment]
hey @jordon31  im trying your script any help please? 

![Screenshot 2023-04-11 231940](https://user-images.githubusercontent.com/34497266/231340059-7827fa8e-0b4b-4f6a-a087-9431339fa285.png)

**Comment by user7590831** [comment]
Looks like you edited the onlyfans-dl.py script while you shouldn't. [As directed in the README](https://github.com/k0rnh0li0/onlyfans-dl#usage), you should set these session variables in the auth.json file.
