### ISSUE TITLE
SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC

### ISSUE THREAD

**Issue by GizmoTheGreen** [k0rnh0li0/onlyfans-dl#23]
randomly get this error, usually on larger files like videos.
resulting in a corrupt file that's skipped next time script is launched.
![image](https://user-images.githubusercontent.com/1146558/106027517-3fcd9f80-60cb-11eb-8cc5-6f2f8b8eaf31.png)

ideas for solution is either to avoid the error somehow.
or possible workarounds
1; check filesize and retry if smaller?
1; download with appended "_temp" on filename and then rename it only on completed download.

**Comment by k0rnh0li0** [comment]
Seems like a Windows thing. Install GNU/Linux.
