### ISSUE TITLE
ERROR: Please refresh the page

### ISSUE THREAD

**Issue by maxc0** [k0rnh0li0/onlyfans-dl#236]
![image](https://github.com/k0rnh0li0/onlyfans-dl/assets/35903396/069d0b74-c2cd-4b07-b6fd-e341cbb57e0a)

I am getting `ERROR: Please refresh the page`. I have redone all the values in auth.json with no luck.

**Comment by merry-hat** [comment]
Change 
```
    dynamic_rules = requests.get(
        'https://raw.githubusercontent.com/DATAHOARDERS/dynamic-rules/main/onlyfans.json').json()
```
to
```
    dynamic_rules = requests.get(
        'https://raw.githubusercontent.com/DIGITALCRIMINALS/dynamic-rules/main/onlyfans.json').json()
```

**Comment by anton1konon** [comment]
> Change
> 
> ```
>     dynamic_rules = requests.get(
>         'https://raw.githubusercontent.com/DATAHOARDERS/dynamic-rules/main/onlyfans.json').json()
> ```
> 
> to
> 
> ```
>     dynamic_rules = requests.get(
>         'https://raw.githubusercontent.com/DIGITALCRIMINALS/dynamic-rules/main/onlyfans.json').json()
> ```

Thank you!!!

**Comment by Walkman100** [comment]
> ```
>     dynamic_rules = requests.get(
>         'https://raw.githubusercontent.com/DATAHOARDERS/dynamic-rules/main/onlyfans.json').json()
> ```
for anyone wondering, this is on line 351 of onlyfans.py, and it works

**Comment by maxc0** [comment]
> Change
> 
> ```
>     dynamic_rules = requests.get(
>         'https://raw.githubusercontent.com/DATAHOARDERS/dynamic-rules/main/onlyfans.json').json()
> ```
> 
> to
> 
> ```
>     dynamic_rules = requests.get(
>         'https://raw.githubusercontent.com/DIGITALCRIMINALS/dynamic-rules/main/onlyfans.json').json()
> ```

Initially it did not work. But I recloned the repo then changed the URL and it start working.

Thanks.
