### ISSUE TITLE
Question: Save Directory

### ISSUE THREAD

**Issue by sourmilk01** [k0rnh0li0/onlyfans-dl#24]
Hello,

I've just used this script but I've been unable to find where photos and videos have been saved.

What would be the default directory and can this be changed at all?

**Comment by sourmilk01** [comment]
After doing a deep search, I found the saved images in my C:\Windows\System32 directory.

Is there any way to change where the script saves to?

**Comment by livkx** [comment]
It creates the directory in the same place the script is invoked from. If you're on Windows, you can for example cd to the directory the script is in e.g. cd `C:\dev\onlyfans-dl.py` and then `python onlyfans-dl.py <username> <token>` and the directory will be created in the C:\dev folder.
