### ISSUE TITLE
API Header issues

### ISSUE THREAD

**Issue by Amnesty1** [k0rnh0li0/onlyfans-dl#240]
I am getting errors when it comes to the auth.json file, I had saw another post about the issue but the solution was that he had edited the scripts and not the json file... i had a clean download and only edited the json and am still coming up with this error.

Traceback (most recent call last):
  File "c:\user\onlyfans-dl-master\onlyfans-dl.py", line 354, in <module>
    API_HEADER = create_auth()
  File "c:\user\onlyfans-dl-master\onlyfans-dl.py", line 50, in create_auth
    with open("auth.json") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'auth.json'

**Comment by jordon31** [comment]
my script its better

https://github.com/jordon31/OF-SCR
