### ISSUE TITLE
Connecting Onlyfans account to GPT chat

### ISSUE THREAD

**Issue by doctorregina** [k0rnh0li0/onlyfans-dl#243]
Hiii,

I have an OnlyFans agency and I would be happy to build Python script to automate chatting with costumers via GPT chat.

Could you please help me to create this code? As far as I know there is no API in Onlyfans website so the data could only be transferred by data scrapping, am I right?

**Comment by maxc0** [comment]
I can do it, but I charge USD 100 per day and I will take 3 months.

**Comment by taux1c** [comment]
ChatGPT does have an api (it's a subscription service I believe) and you could make requests and pass information back and forth without the api but it would be unreliable at best. (I wrote a discord bot that was able to answer questions via chatGPT.) 

For what you're wanting you would have to keep the requests separate this means you either need async programing or you need 1 instance per account. So what you were quoted isn't really far fetched. It's very similar to my rates as well.
