### ISSUE TITLE
Not all videos on profile being downloaded

### ISSUE THREAD

**Issue by Speaker4TheD3ad** [k0rnh0li0/onlyfans-dl#247]
Not all videos on a profile are being downloaded. Specifically newer videos. 

It's strange because it got new Streams that were added but not some new videos. 
I can see them on the users wall but they are not being downloaded. 

Profile has 528 video downloader sees 521 video posts. May 12th is the last video it is finding. There have been 20+ more posted since. 519 Videos actually downloaded.

Reproduces on multiple profiles

**Comment by hoppalotta2** [comment]
having a similar problem.  appears to be onlyfans latest tech solution to ripping their content.  the videos are loading in individual components and then being compiled in the browser.  not sure if anyone has looked into a way around this?

**Comment by Speaker4TheD3ad** [comment]
I think I found the issue after some googling, DRM unfortunately. OF implented a content blocker making it significantly harder to rip videos.

**Comment by Speaker4TheD3ad** [comment]
I am not sure of the logistics, but this is better than other solutions as far as download speeds and naming etc. Would be cool if we could add the DRM key stuff to this.

**Comment by Oggy512** [comment]
> I think I found the issue after some googling, DRM unfortunately. OF implented a content blocker making it significantly harder to rip videos. The solutions I have found online require 2 files you have to rip from an android phone to be able to download the DRM videos.

Would you mind sharing links/background to those solutions?

**Comment by jsquizz** [comment]
seeing this with pics
