### ISSUE TITLE
Not all subscriptions showing up

### ISSUE THREAD

**Issue by svxnsvxnsvxn** [k0rnh0li0/onlyfans-dl#249]
Only older Subscriptions (before August) showing up in the downloadable list.

**Comment by RubenZafraCactus** [comment]
Yes please, can someone share some light? Happened to me today

**Comment by RubenZafraCactus** [comment]
@svxnsvxnsvxn Looking at the script I managed to fix it. Looks like the limit is not correct. For instance I added a +2 in this line

`SUB_LIMIT = str(user_me()["subscribesCount"]+2)` for me its line 163 in the get_subs function. 

That made the suscriptions appear. You can try that.

**Comment by svxnsvxnsvxn** [comment]
@RubenZafraCactus wow that fixed it. Thank you so much!
