### ISSUE TITLE
Doesn't seem to be picking up new subs

### ISSUE THREAD

**Issue by hoppalotta2** [k0rnh0li0/onlyfans-dl#251]
Is anyone else seeing that new subscriptions are not populating in the list available to download?

Is there a reason for this?

**Comment by peddanet** [comment]
yes me too! Is there a known update time before it is available (so maybe sth like wrong database table which is later updated?)

**Comment by junobite** [comment]
Might be slightly more complicated to setup for some people but this works and downloads DRM protected content [https://github.com/sim0n00ps/OF-DL](https://github.com/sim0n00ps/OF-DL)

**Comment by peddanet** [comment]
Ok it has nothing to do with updates, still missing! Maybe the tool does not get an updated list, so that of is fooling the tool? Or is it that some accoiunts are completely under DRM?

@junobite solution is nice , but I am working from linux! Unfortunately....this is a .Net7 windows app..

**Comment by peddanet** [comment]
@junobite @MiMmmmiiii @hoppalotta2 @forsakendaemon 

[Dotnet 7.0 console app](https://github.com/sim0n00ps/OF-DL)
I have managed to download dotnet-sdk-7.0 and the bento4 tools and installed it on Ubuntu. It worked straightforward and I could save time using the auth.json of this project!:

- [stackoverflow install bento4 ubuntu](https://superuser.com/questions/1670150/how-to-install-bento4-tools-on-ubuntu#answer-1670248) 
-- dependency cmake must be installed (apt install cmake)
- [yt-dlp_linux as executable x64 binary ](https://github.com/yt-dlp/yt-dlp)
- ffmpeg dependency via apt install
- auth.json: 
```
{
  "USER_ID": "123456789",
  "USER_AGENT": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/119.0",  
  "X_BC": "[get it from description or from already configured auth.json from this project]",
  "COOKIE": "auth_id=123456789; sess=[your session id]",
  "YTDLP_PATH": "/usr/local/bin/yt-dlp_linux",
  "FFMPEG_PATH": "/usr/bin/ffmpeg",
  "MP4DECRYPT_PATH": "/usr/local/bin/mp4decrypt"
}
```
- I have managed to copy the yt-dlp_linux to /usr/local/bin: 
```
$ chmod +x  
$ sudo cp -rvf yt-dlp_linux /usr/local/bin/
``` 
- Finally I cloned the OF DL and build 
```
$ git clone https://github.com/sim0n00ps/OF-DL.git
$ cd OF-DL 
$ dotnet publish -r linux-x64 -c Release --self-contained false
```
- For any unknown reason, auth.json and config.json are not part of the published console app. I got it from the [releases zip](https://github.com/sim0n00ps/OF-DL/releases/download/OFDLV1.7.44/OF.DL.V1.7.44.zip) and extract them to the publish folder 

And voila, it worked perfectly! It was my first port of a c# app to Ubuntu and I was scared, it worked so straight forward, out of the box. So starting the process from publish folder:
`$ ./OF\ DL`

**Comment by puckslane** [comment]
This isn't a OF issue - it is a script issue. 

The latest sub is being truncated from the list. If you are facing this, after you subscribe to anyone you want to DL, subscribe to someone free after it. The one you want will now be listed last. You can then unsub the free one, add another one, then resub to a free one to get the list correct

I expect its an issue with the array being shown, but I am not in the headspace to debug code. If someone can but that would be great :D
