### ISSUE TITLE
ERROR: Please refresh the page

### ISSUE THREAD

**Issue by svxnsvxnsvxn** [k0rnh0li0/onlyfans-dl#256]
Just getting this message 

![error](https://github.com/k0rnh0li0/onlyfans-dl/assets/114740929/2a8fa16a-0c92-4af7-ae05-6a5c5b870b67)

Python 3.11 on PyCharm

**Comment by squiddog** [comment]
That makes 2 of us.

**Comment by dumpbox76** [comment]
3 now.
