### ISSUE TITLE
error

### ISSUE THREAD

**Issue by andrerdxd** [k0rnh0li0/onlyfans-dl#28]
whenever i try to run it i get this error

onlyfans-dl-master\onlyfans-dl.py", line 16, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by k0rnh0li0** [comment]
`python -m pip install requests`

**Comment by andrerdxd** [comment]
thanks that fixed the error but now i get 

Getting user auth info...

ERROR: Access denied.

and yes i updated the user agent
