### ISSUE TITLE
Only Downloading 100 Posts

### ISSUE THREAD

**Issue by Kiranaide** [k0rnh0li0/onlyfans-dl#3]
When i use the script, it just downloading from 100 posts, and if im redownload it to get more post it just saying profile exist not downloading more posts

**Comment by hugeband** [comment]
Modify this variable POST_LIMIT

**Comment by RobVor** [comment]
Changing the post limit doesn't change the number of downloads.

**Comment by PythonLimited** [comment]
> Changing the post limit doesn't change the number of downloads.

Probably an api limitation then.

**Comment by yambu** [comment]
Fix with my new fork https://github.com/yambu/onlyfans-dl

**Comment by k0rnh0li0** [comment]
Fixed in #7
