### ISSUE TITLE
Access denied.

### ISSUE THREAD

**Issue by Vancore** [k0rnh0li0/onlyfans-dl#30]
Not sure if you checked the recent version of OnlyFans, it seems they updated their services.

Everytime I try to fetch data it tells me "Error: Access denied." and logs me out of the Website.

Could you maybe check that? So far: Thank you so much for the great work! Amazing! :)

**Comment by Vancore** [comment]
Just tested with incognito mode, it works in incognito mode.

**Comment by shikamaruxll** [comment]
Hello @Vancore i'm having the same exact issue, could you help me ?

**Comment by Vancore** [comment]
I don't know if this should be closed @k0rnh0li0 , it is not solved. I tried on different occasions and right now it is also not working for the incognito mode anymore. Any ideas?
