### ISSUE TITLE
See README for instructions.

### ISSUE THREAD

**Issue by rumtumtugger91** [k0rnh0li0/onlyfans-dl#31]
I keep getting this? What am i doing wrong? :/

**Comment by k0rnh0li0** [comment]
There are two lines in that error message. You're either missing the profile name or your auth token.

**Comment by rumtumtugger91** [comment]
can i know the format of the profile name to key in?
I'm assuming is the name after 'onlyfans.com/<profilename>'?
I do have the auth token and followed the instructions.
