### ISSUE TITLE
Route not found Firefox 85

### ISSUE THREAD

**Issue by pwnage-boop** [k0rnh0li0/onlyfans-dl#32]
Seems to be an issue with either OF api or Firefox85, get a route not found error when running since latest firefox update. user agent is "Mozilla/5.0 (X11; Linux x86_64; rv:85.0) Gecko/20100101 Firefox/85.0". Additionally I definitely have the correct token as the tool only throws this message after the "Getting user auth info" and the "Getting target profile info" readouts.

**Comment by k0rnh0li0** [comment]
Unable to reproduce
