### ISSUE TITLE
Possible features: more options and logs

### ISSUE THREAD

**Issue by ontionas** [k0rnh0li0/onlyfans-dl#34]
First off, great library. I've been ripping tons of pictures and videos.

It might be helpful in some cases to be able to specify what type of content you want to download (pictures or videos). Some users have a ton of crap pictures/ videos and I might just want one or the other. Though the more data the better, I guess. Just a thought

Another thing I like to do is sort the videos afterwards into folders for *research purposes*. This breaks the feature which does not re download content you already have.  It might be helpful to either read that list from a log file in that user's directory, or allow the script to traverse into directories to find file names

**Comment by Eviepayne** [comment]
I can second this. looking at the code I think it'd be fairly trivial to add argparse to this for some custom options.
I've already ghetto edited my branch to include custom directories.

**Comment by Voldrix** [comment]
An option to separate photos into folders by post/album would be great.

**Comment by jordon31** [comment]
@Voldrix  view my script   https://github.com/jordon31/OF-SCR 

i completely renewed it but i could not put
stories
messages and split free/paid messages and posts  -- I could not


You can help me with my script?
