### ISSUE TITLE
Access Token & Profile ID Placing || Help a Noobie Here

### ISSUE THREAD

**Issue by Signup-pawan** [k0rnh0li0/onlyfans-dl#38]
Hey, first of all, thanks for the code.

I'm a noobie in Python. I have grabbed and placed UserAgent but I don't know where to post the Access Token & Profile in the code?

Can anyone help me with the screenshots? (If Possible.) or tell me where should I post access token and Profile ID in script exactly?

Thanks!

![image](https://user-images.githubusercontent.com/55138565/108773351-36c5d600-7584-11eb-80c4-48ec1e4b8b3b.png)

**Comment by Signup-pawan** [comment]
@k0rnh0li0 Hey, I don't know why the issue was closed without giving any reply. Can you plz let me know?

**Comment by sufyazi** [comment]
In case you haven't figured it out yet. The answer to your question is literally in the screenshot. In the terminal programs require arguments to run.

In this case, the arguments, as detailed in the README is as follows

```python xxxxx.py <profile ID> <access token>```

This means you should type your run command this way:

```python path/to/.py/file exampleprofileID accesstoken2738273283```

The spaces are important, as does the order.
