### ISSUE TITLE
See README for instructions.

### ISSUE THREAD

**Issue by Signup-pawan** [k0rnh0li0/onlyfans-dl#40]
I have opened the issue but it was closed without providing any solution. So was hoping to get an answer for this one atleast.

I always get this error. Can anyone tell me where exactly I need to post 
`<profile> <accessToken>` in the script? what else are we need to insert in the script?

Thanks!

![image](https://user-images.githubusercontent.com/55138565/108897401-10637180-763c-11eb-95a7-cc249f537db6.png)

**Comment by derPiepmatz** [comment]
What exactly did you enter there? It's not quite clear, what you did enter and what the response of the script is.

**Comment by sufyazi** [comment]
Again, you don't post those things in the script. They are posted as 'arguments' for the program during runtime.

I posted an answer to your last question. Please try again.

Also not sure what platform you're running this in, so I don't know what you run in the terminal. I have never seen !python used to run python command before so either I'm not aware that this is Windows-based quirk (I used UNIX-based, MacOS system to be specific), or you're making a mistake and should lose the ! when invoking python.
