### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by quarz12** [k0rnh0li0/onlyfans-dl#41]
i am getting: 
Saving profile info...
Finding photos...
Traceback (most recent call last):
  File "onlyfans-dl.py", line 225, in <module>
    photo_posts = api_request("/users/" + PROFILE_ID + "/posts/photos", getdata={"limit": POST_LIMIT})
  File "onlyfans-dl.py", line 78, in api_request
    beforePublishTime = list_extend[posts_num-1]['postedAtPrecise']
IndexError: list index out of range

**Comment by derPiepmatz** [comment]
I think I'll also had this issue, try to pull the newest version and see if this works now.

**Comment by k0rnh0li0** [comment]
This is an issue with how the "pagination" was implemented. I haven't worked on fixing this because I haven't reproduced it yet, but what's happening is that the "pagination" scheme is resulting in an empty list at some point, causing this error.

**Comment by iannacone** [comment]
add `if posts_num > 0:` as an additional check at line 85 otherwise it tries to get the `posts_num-1` index which is -1 in that case. sorry if i do not create a pr.

**Comment by Eviepayne** [comment]
Ran into this as well. It seems to only happen to certain models. I initially thought it was being rate-limited.
