### ISSUE TITLE
module import request

### ISSUE THREAD

**Issue by Mang0Monkey** [k0rnh0li0/onlyfans-dl#45]
```
  File ".\onlyfans-dl.py", line 16, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

When I run `python3 onlyfans-dl.py` I get that error in return. Not sure why but line 16 says import requests, and it looks fine to me. But that return error keeps popping up.

**Comment by ThatJerkPat** [comment]
You need to import requests

example: python -m pip import requests
It will download and import the requests library and the command should work after that
