### ISSUE TITLE
ERROR: Acess denied and logout

### ISSUE THREAD

**Issue by ontionas** [k0rnh0li0/onlyfans-dl#46]
Been using this without issue for a few weeks, and all of a sudden I started getting `ERROR: Access denied.` messages and my session would be logged out

**Comment by thomasthespider** [comment]
I'm getting the same too.

**Comment by Mang0Monkey** [comment]
I can't even get it anything to run. Wonder if that is why. That or unless I am not doing this correctly

**Comment by k0rnh0li0** [comment]
Can't reproduce, werks for me. Make sure you set the user agent correctly and that you use the correct access token.
Your user agent may have changed if you updated your browser.

**Comment by ontionas** [comment]
Confirmed updating user-agent fixed the issue
