### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by JoeSchmoe2021** [k0rnh0li0/onlyfans-dl#48]
File "./of.py", line 186
    dwnld_stats = f"{cur_count}/{total_count} {round(((cur_count / total_count) * 100))}% " + \
                                                                                          ^
SyntaxError: invalid syntax

the arrow is pointing to the 2nd ". I've tried removing and recreating both ", but no dice. Any ideas? 

Python 2.7.18
Linux

**Comment by k0rnh0li0** [comment]
Hello, this is a Python 3 script, but you're running it in Python 2
