### ISSUE TITLE
path.rfind is NoneType

### ISSUE THREAD

**Issue by manik002** [k0rnh0li0/onlyfans-dl#50]
Hi, first thank you a lot I have been able to use the script for an account.
I'm trying again with another one and getting this error:

`Traceback (most recent call last):
  File "c:/Users/.../script.py", line 256, in <module>
    download_public_files()
  File "c:/Users/.../script.py", line 118, in download_public_files
    id = get_id_from_path(source)
  File "c:/Users/.../script.py", line 159, in get_id_from_path
    last_index = path.rfind("/")
AttributeError: 'NoneType' object has no attribute 'rfind'`

I get correctly authenticated and the folder structure gets created. This appears after downloading the avatar.

**Comment by adibclone** [comment]
Same.. I have that issue too

**Comment by arbyyyyh** [comment]
I've found that someone I know to have changed their name doesn't work but someone else who hasn't changed their name works fine.

**Comment by derPiepmatz** [comment]
I don't know how to reproduce this. May anyone of you post a name in here that does not work and throws this error. It can be any since the public files should work even if I don't sub in.

**Comment by arbyyyyh** [comment]
The user I was working with was neongenesexxt. Name was formerly
neongenesext. As I recall, it created the folder structure, but there was
no data. I also tried using the profile number, but no luck. hungtwinks
also caused an issue. Something about something was too long.

**Comment by derPiepmatz** [comment]
I checked. It seems it has nothing to do with a change name. I just did not check for missing public files. Take a look at my [branch](https://github.com/derPiepmatz/onlyfans-dl/tree/skip-missing-public-files). Download the .py from there and try it.
