### ISSUE TITLE
Download images using filename rather than media ID to avoid duplicates

### ISSUE THREAD

**Issue by gamer13766** [k0rnh0li0/onlyfans-dl#52]
Hi there, great program, been running well so far.

I've noticed that the images are downloaded using the media ID (eg 133742069) rather than the image name (2098x3088_9fd75ce7fcf595b5008759544cf0d0fe.jpg) and this results in a lot of duplicates. I'm not entirely sure how OF does it but I've downloaded a profile and used a duplicate finder tool. Cleared out a bunch of files, and then re-ran onlyfans-dl and the files re-appeared.

Just wondering how easily this can be changed?

**Comment by derPiepmatz** [comment]
Could it be that the creator you're following reposted pictures? The file name would be the same but the id different.

If so, that would be a bad choice. Some creators may upload just files named `unknown.jpg` or something and then you would lose images.

**Comment by gamer13766** [comment]
Possibly, although it happens with a number of creators, not just one. There was a browser plguin I used to use which downloaded using the image name - whatever the file name is called, it's renamd with the dimonsions and then a random number (some sort of GUID, I assume), so if multiple unknown.jpgs were uploaded OF would rename them

**Comment by derPiepmatz** [comment]
Yeah, it seems that OF names the files themselves. Sadly I cannot reproduce this but I made [branch](https://github.com/derPiepmatz/onlyfans-dl/tree/download-images-with-image-name) that applies your requested changes. Take a look. Just make sure that your `profiles` directory is renamed so you don't have a ton of duplicates.

**Comment by gamer13766** [comment]
Awesome, thank you very much. I will give it a shot now.

**Comment by derPiepmatz** [comment]
Please tell me if that makes a difference

**Comment by gamer13766** [comment]
Afraid not. Downloaded one I'm subbed to, ran a duplicate check on the newly downloaded folder and found numerous duplicates.

Each picture is the same, even though it has different file names.

![image](https://user-images.githubusercontent.com/80432320/111380049-c51d0b80-869b-11eb-946a-d69a77ad73d9.png)

**Comment by derPiepmatz** [comment]
You did not use the branch I linked to download your files. It should look more like this: 
![image](https://user-images.githubusercontent.com/3590829/111391326-ac6d1f80-86b4-11eb-896e-1accfd61e38a.png)
Make sure you take the .py from the branch `download-images-with-image-name` in my repo.

**Comment by gamer13766** [comment]
Ah, I'm sorry, I didn't see the "download-images-with-image-name" branch.

This does have the same issue I'm afraid.

![image](https://user-images.githubusercontent.com/80432320/111398168-dde8e980-86ba-11eb-9b0c-0724ebaab22f.png)

**Comment by derPiepmatz** [comment]
Hmm. I'm pretty sure these are different uploads then. To fix this it would need to detect duplicates. But on OF you can't find hashes to do so. So we would need a custom solution to this. I may look into this and add some json file storing all hashed duplicates.

**Comment by k0rnh0li0** [comment]
This isn't an issue with the script, the profiles you're downloading are uploading multiples of the same picture. The script simply downloads all pics/videos an account has uploaded.
