### ISSUE TITLE
help please?

### ISSUE THREAD

**Issue by theviergod** [k0rnh0li0/onlyfans-dl#53]
new to python could someone help me get this working? plez

**Comment by gamer13766** [comment]
What have you tried so far?

**Comment by Escopy88** [comment]
1) Go to the directory where you keep the onfans-dl program.
2) Hold shift then right click and in the drop down menu select "Open Powershell window here".
3) Type "python onlyfans-dl.py", then hit enter.
4) Type "./onlyfans-dl.py <profile> <accessToken>", then hit enter. It will start downloading into a folder it creates called "profiles".

- The values for profile and accessToken are found in the ReadMe file that's included in the download. follow the instructions in the ReadMe
-  If you get an error after step 3, you may have to download the python libraries to your PC and add them to the shell. you can just google how to do this it's simple

Hope that helps. You have to kind of figure it out.
