### ISSUE TITLE
Cant run it

### ISSUE THREAD

**Issue by RamaZenda** [k0rnh0li0/onlyfans-dl#54]
Hello there, great repo, but im totally new at python and I would need some help to run the strings, I got all the values needed, but everytime I try to run it I get a syntax error. what command should I type to run it? I got Python 3.9
Thank you for your help !

**Comment by RamaZenda** [comment]
C:\Users\User\Documents>py onlyfans-dl.py 'profile' 'useragent'
  File "C:\Users\Wanam\Documents\O\onlyfans-dl.py", line 7
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax

**Comment by RamaZenda** [comment]
C:\Users\User\Documents>py onlyfans-dl.py 'profile' 'useragent'
File "C:\Users\Wanam\Documents\O\onlyfans-dl.py", line 7
<!DOCTYPE html>
^
SyntaxError: invalid syntax

**Comment by RamaZenda** [comment]
C:\Users\User\Documents>py onlyfans-dl.py 'profile' 'useragent'
File "C:\Users\Wanam\Documents\O\onlyfans-dl.py", line 7
'<!DOCTYPE html>
^
SyntaxError: invalid syntax

**Comment by RamaZenda** [comment]
<!DOCTYPE html>
thats whats missing

**Comment by RamaZenda** [comment]
<  !DOCTYPE html>
thats whats missing

**Comment by Escopy88** [comment]
Check the most recent closed issue where this question was asked. I put a brief tutorial in there.
