### ISSUE TITLE
OSError: [Errno 63] File name too long

### ISSUE THREAD

**Issue by sufyazi** [k0rnh0li0/onlyfans-dl#55]
```Saving profile info...
Downloading avatar...
Traceback (most recent call last):
  File "onlyfans-dl.py", line 256, in <module>
    download_public_files()
  File "onlyfans-dl.py", line 123, in download_public_files
    download_file(PROFILE_INFO[public_file], path)
  File "onlyfans-dl.py", line 154, in download_file
    with open("profiles/" + PROFILE + path, 'wb') as f:
OSError: [Errno 63] File name too long: 'profiles/thesharok/avatar/atwg3mn4jppu0kprsqoyuc7fhd4epmgi1586293483.jpg?Tag=2&Expires=1647237840&Signature=Q4UE~o7Sr~gnNfEaMwXrUZYvXWoi1qqiKl4XTTqgoKFVVWTW7vvwyZyMujB8ym6gp4hyRFHphBtLg0TFY6fFQDrSK3dQvb60raDS16SxD4BFp2VNgWoRvPFRdWp549H~xO0ZNr4z6Vo2OpOYndae2D7TYj3GF1fafCQT4FcbZ4SYty01rCSOBKZKl28zh2cNAvC6nXbFAKmjloBuEehoFqlU7MlL-DlBGdwpWPDFTiP832NallYrz~XNCphjzmZBVEQ0Ovy0alvPbqQcBnyaRzGvbks3vtVPQ6IKVi9SSJoof0enu7r8Hj9sPHSylmuwPa2qfwkGI74~8KKNozh-Mg__&Key-Pair-Id=APKAJZU4IULC2OKULHGA'
```

Hi, I've been using this very nifty program for a while now and have scraped a few profiles I subscribed. However, this one recent profile I was trying to scrape, keep giving me this 'file name too long' error and I've looked at the python script but I'm too much of a beginner programmer that I am not sure what to do to fix this error. Python throws this error up and then stops downloading. Can you quickly help me with this whenever you have time?

**Comment by derPiepmatz** [comment]
Oh, I'm pretty sure where that came from. I'll look into it. c:
I'll post something down here when I have a fix for that.

**Comment by derPiepmatz** [comment]
It looks like the file type detection did not work correctly. I changed it a bit on this [branch](https://github.com/derPiepmatz/onlyfans-dl/tree/fix-public-file-names-detection). Take a look if this helps.

**Comment by sufyazi** [comment]
Hi @derPiepmatz It works perfectly now! Thank you!
