### ISSUE TITLE
error profiles exists,  Please remove it and try again.

### ISSUE THREAD

**Issue by maneanem** [k0rnh0li0/onlyfans-dl#6]
hi! i get that error

Getting user auth info...
Getting target profile info...

onlyfans-dl is downloading content to profiles/barbon_poblano!

ERROR: profiles/barbon_poblano exists.
       Please remove it and try again.

**Comment by yambu** [comment]
Try my new fork https://github.com/yambu/onlyfans-dl

**Comment by k0rnh0li0** [comment]
Fixed in #7
