### ISSUE TITLE
Access denied

### ISSUE THREAD

**Issue by ahmetselman** [k0rnh0li0/onlyfans-dl#60]
I do all steps what you mentioned on readme file. I entered my user agent in source code. Get auth token form browser and when i m trying to call your script it says:

Getting user auth info...
ERROR: Access denied.

When i turn back to browser(which i logged in before) and click anywhere on onlyfans it turns back me to the login screen. So i think the session has gone on browser too.

**Comment by Eviepayne** [comment]
I had the same issue.
Revert this commit
https://github.com/k0rnh0li0/onlyfans-dl/commit/51adbaab820f6c4fbbdecffcd275fa6b840c2fff

**Comment by JoeSchmoe2021** [comment]
Yep same here. Logged me out of browser too. probably an update to the API on the OF side, as I'm not running the latest version

**Comment by Eviepayne** [comment]
Update turns out the issue wasn't the commit. When I pulled it changed the user agent and forgot to change it back.
Make sure you change your user agent to match the browser you got the access token from.
