### ISSUE TITLE
Access denied 

### ISSUE THREAD

**Issue by bnsave100** [k0rnh0li0/onlyfans-dl#61]
everything I pasted as given instructions and ran the script + after following error my account got logged out : (

~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~ I AM THE GREAT KORNHOLIO ~
~  ARE U THREATENING ME??  ~
~                          ~
~    COOMERS GUNNA COOM    ~
~    HACKERS GUNNA HACK    ~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Getting user auth info... 

ERROR: Access denied.

**Comment by Eviepayne** [comment]
check to make sure your useragent is correct.

**Comment by bnsave100** [comment]
yeah it was correct i used https://whatismybrowser.com/detect/what-is-my-user-agent

**Comment by bnsave100** [comment]
alright this worked well there was extra space i left mistakenly now the download is working
