### ISSUE TITLE
Completely Lost

### ISSUE THREAD

**Issue by Malitahj** [k0rnh0li0/onlyfans-dl#64]
I got my user agent, opened the onlyfans-dl.py file in VS Code and changed it.
I opened command prompt as an administrator.
I made sure to run [python -m pip install requests]
I cd'd to the location of onlyfans-dl.py
I ran the command [onlyfans-dl.py sayanozzy k3v6c845ucuodj7fvo71plrmsq]
It opened a new window for half a second that said

Usage ./onlyfans-dl.py <profile> <accessToken>
See README for instructions

I looked through it again and repeated all the steps but this time I made a .bat file that included the line [onlyfans-dl.py sayanozzy k3v6c845ucuodj7fvo71plrmsq] but the same thing happened again.

**Comment by TaquitoSlayer** [comment]
when u down bad but dont know how to use python

**Comment by Malitahj** [comment]
I'm down terrible

**Comment by TaquitoSlayer** [comment]
u gotta put python in front of the command homie
`python ./onlyfans-dl.py sayanozzy k3v6c845ucuodj7fvo71plrmsq`
think of me when u go off thanks
