### ISSUE TITLE
How can I fix this | Console/Terminal :  Finding photos... Found 0 photos. Finding videos... Found 0 videos. Finding archived content... Found 0 archived posts. ERROR: 0 posts found.

### ISSUE THREAD

**Issue by dimer191996** [k0rnh0li0/onlyfans-dl#65]

**Comment by ontionas** [comment]
Only way I have accidentally recreated this is by spelling the user's name wrong. Include more information in your issues, like your input. )And not all in the title lol)

**Comment by dimer191996** [comment]
is this code bypass the payment wall ?

**Comment by eath4n** [comment]
> is this code bypass the payment wall ?

No, it's intended to fetch content you are subscribed to.
