### ISSUE TITLE
< was unexpected at this time.

### ISSUE THREAD

**Issue by sgaurav510** [k0rnh0li0/onlyfans-dl#67]
C:\Users\sgaur\Downloads\onlyfans-dl-master\onlyfans-dl-master>./onlyfans-dl.py <nastiya> <jfp8van18g659hke2hotv2aebj>
< was unexpected at this time.

requirement already satisfied when i install the requirement

**Comment by AnakinCaesar** [comment]
dont put the <> in there. just plain name and token no '<' '>'
