### ISSUE TITLE
App token not working

### ISSUE THREAD

**Issue by Trevor49** [k0rnh0li0/onlyfans-dl#68]
I get the following error when trying to run it.
ERROR: Application token is required.

I have followed the steps to get the token using the web console. I've tried with two different browsers, Opera, and Chrome. Both also show the Error: WebSocket is already in CLOSING or CLOSED state in the web console, shortly after obtaining the App token.

I'm not that experienced with python, so any help would be appreciated.

**Comment by ontionas** [comment]
As of today I am getting a `null` response when I use the `localStorage.getItem("accessToken")` method, maybe its related. Never happened to me before

**Comment by Trevor49** [comment]
I'm able to run that command to get the token, but then it doesn't work for some reason

**Comment by Agugalera** [comment]
Same here. The accessToken is not being saved in Local Storage in my case. Clearly it is an OF's bug.

Could it has something to do with Google Login?

**Comment by kovalevdo** [comment]
I was able to get the token, but it didn't work. Then I logged out and signed in again, and now the command returns null. Maybe OF has changed their authentication method?

**Comment by k0rnh0li0** [comment]
There's definitely something wrong here, I'll check it out

**Comment by k0rnh0li0** [comment]
They no longer store access tokens in localStorage. I was able to find the token a different way, but it's not as easy for users to do. I'll look into this more tonight and find a new easy way to get the access token

**Comment by Purpleshithead** [comment]
Also getting null when requesting the access token, please look into this

**Comment by k0rnh0li0** [comment]
I have pushed a commit to address OnlyFans' change to their auth scheme, as well as updated the README with instructions on how to get your auth token now. The script works for me now, let me know if you have any lingering problems

**Comment by ontionas** [comment]
New method works for me

**Comment by jamhouse2009** [comment]
token is working for me now but it now says ERROR: Wrong user. and then logs me out in the browser
