### ISSUE TITLE
Error: wrong user

### ISSUE THREAD

**Issue by jamhouse2009** [k0rnh0li0/onlyfans-dl#70]
token is working for me but it now says ERROR: Wrong user. and then logs me out in the browser.
![Screenshot_1](https://user-images.githubusercontent.com/64562909/113644624-2e68bc80-9653-11eb-8df4-15bad3abc2a7.jpg)

**Comment by k0rnh0li0** [comment]
Make sure your user agent is right, the script is working for everyone else now

**Comment by lukeadair** [comment]
I have the same error. I've verified I have the correct user agent as instructed. I've even tried different browsers

**Comment by k0rnh0li0** [comment]
Hmmm, try logging out, clearing your cookies/cache for onlyfans, and logging back in?

**Comment by lukeadair** [comment]
Tried logging out. I didn't clear the cache, but did use a browser that I had never logged into OF before

**Comment by k0rnh0li0** [comment]
Interesting, what browser are you guys using?

**Comment by lukeadair** [comment]
first chrome, then firefox

**Comment by jamhouse2009** [comment]
i double checked my user agent and cleared cookies and cache and still same error. i tried using both firefox and chrome

**Comment by lukeadair** [comment]
Chrome header: https://paste.ofcode.org/DsEcqdhUUBYZJi5aaC354G

**Comment by k0rnh0li0** [comment]
Just to be sure, did you guys pull the latest version of the repo with `git pull` ?

**Comment by lukeadair** [comment]
sure did

**Comment by lukeadair** [comment]
omg, so sorry. Just pulled again and that fixed it. I had just cloned the repo maybe a few hours ago

**Comment by k0rnh0li0** [comment]
:D glad it works now!
