### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Lingaaah** [k0rnh0li0/onlyfans-dl#72]
Hey there, 
I'm pretty new to using python so my error is probably simple as anything to fix but I couldn't figure it out

I think my issue is not knowing where to exactly enter which data. 
Is it possible you could tell me which line of code to enter the
profile name
access token 
user-agent

Thank you, sorry for the hassle

**Comment by Lingaaah** [comment]
The error I'm getting when running the program is just:

Usage: ./onlyfans-dl <profile> <accessToken>
See README for instructions.

Process finished with exit code 0

**Comment by ruchitooh** [comment]
Same error, trying to understand what am I doing wrong. I already paste de value of sess cookie on <accessToken> and username on <profile> found in line 203. Any hint will be appreciate.
![image](https://user-images.githubusercontent.com/82008176/113648899-0a0ce000-9653-11eb-90ad-d583554f04cc.png)

**Comment by Eviepayne** [comment]
remove the carrots. (<>)
