### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by l3ounce** [k0rnh0li0/onlyfans-dl#73]
...\Desktop\onlyfans-dl-master>onlyfans-dl.py <profile> <access token>
  File "...\Desktop\onlyfans-dl-master\onlyfans-dl.py", line 44
    API_HEADER = { Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:87.0) Gecko/20100101 Firefox/87.0
                                                                ^
SyntaxError: invalid syntax

I copied the User Agent from https://whatismybrowser.com/detect/what-is-my-user-agent
however, I'm getting the syntax error above. I'm sure I'm not seeing something obvious. Thanks in advance

**Comment by k0rnh0li0** [comment]
It should be `API_HEADER = "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:87.0) Gecko/20100101 Firefox/87.0"`

**Comment by l3ounce** [comment]
Thank you.
