### ISSUE TITLE
accessToken is returning null

### ISSUE THREAD

**Issue by Pwnager12345** [k0rnh0li0/onlyfans-dl#74]
when I type 
localStorage.getItem("accessToken");
into my browser console it just returns "null"

**Comment by Eviepayne** [comment]
Works for me.
Are you logged into onlyfans?
![image](https://user-images.githubusercontent.com/59463208/113661417-08074900-9674-11eb-98de-b800ac0598d0.png)

**Comment by k0rnh0li0** [comment]
OnlyFans has changed how they handle access tokens - see the readme for updated instructions on how to get your auth token. Be sure to pull the latest version of the repo with `git pull`

**Comment by Eviepayne** [comment]
It literally just changed for me as well.
You can use this plugin to get cookies easily if you don't want to do the readme method
https://add0n.com/cookie-editor.html
Top corner has links for each browser.
