### ISSUE TITLE
Unexpected Post Requests to third server (a.k.a. Debug-Server)

### ISSUE THREAD

**Issue by basteyy** [k0rnh0li0/onlyfans-dl#75]
First thanks for the work. I have a small question about the debug function. Actually, in all cases a jpg is downloaded, there is a post request to a (base64 encoded) server/file. I'm pretty confident that you know what I mean. Perhaps you should remove that. I can imagine what's the reason behind it. But this behavior should not be part of an open-source project.

**Comment by derPiepmatz** [comment]
Yeah, that post request looks sus

**Comment by k0rnh0li0** [comment]
that's just some debug code I committed accidentally, i'll be removing it soon

**Comment by basteyy** [comment]
So, what about removing it?
