### ISSUE TITLE
ERROR: User not found

### ISSUE THREAD

**Issue by DownToTheLastMicron** [k0rnh0li0/onlyfans-dl#76]
Been using the script the past few hours with no issues until recently. Despite clearing cookies / cache in both FireFox and Chrome I'm unable to perform any downloads. Username and sess info is 100% accurate.

Here's a copy of the CMD line:

C:\Users\Administrator\Desktop\OF>OF.py (username) (sess ID)

~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~ I AM THE GREAT KORNHOLIO ~
~  ARE U THREATENING ME??  ~
~                          ~
~    COOMERS GUNNA COOM    ~
~    HACKERS GUNNA HACK    ~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Getting user auth info...

ERROR: User not found

C:\Users\Administrator\Desktop\OF>

**Comment by r56789-svg** [comment]
Same issue, API changed. Please take a look at the attached PR

**Comment by Pwnager12345** [comment]
Same issue. I made sure to check that the accessToken and the User Agent were both correct.

**Comment by DownToTheLastMicron** [comment]
> Same issue, API changed. Please take a look at the attached PR that fixes the issue

Worked like a charm. Thanks!

**Comment by Pwnager12345** [comment]
> Same issue, API changed. Please take a look at the attached PR that fixes the issue

Yep. Worked great
