### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by og080121** [k0rnh0li0/onlyfans-dl#8]
Hi,
When I run the code in cmd, it returns:

C:\Users\user\Documents\ONF\New folder\onlyfans-dl>onlyfans-dl.py skye-fetish knc41dhr7rdsno8u07o38m4e11
Traceback (most recent call last):
  File "C:\Users\user\Documents\ONF\New folder\onlyfans-dl\onlyfans-dl.py", line 16, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

Any help would be appreciated - I am pretty bad with coding and i've never used python.

**Comment by Entroponaute** [comment]
Hello, 

You need to install a script for requests.
You can check this page : https://pericror.com/software/importerror-no-module-named-requests/

Have a nice day !
