### ISSUE TITLE
Error when user has 100 or more archived posts

### ISSUE THREAD

**Issue by redditdoe** [k0rnh0li0/onlyfans-dl#82]
I have been using the script with great success. Although I have encountered a problem where a model has 100 archived posts and it seem to break the script. 

`Finding archived content... Traceback (most recent call last):
  File "C:\Users\matt\Downloads\onlyfans-dl-master\onlyfans-dl.py", line 275, in <module>
    archived_posts = api_request("/users/" + PROFILE_ID + "/posts/archived", getdata={"limit": POST_LIMIT})
  File "C:\Users\matt\Downloads\onlyfans-dl-master\onlyfans-dl.py", line 86, in api_request
    beforePublishTime = list_extend[posts_num-1]['postedAtPrecise']
IndexError: list index out of range`

I also find that it is not downloading all of the photos or images from a models page do you know why that might be?

**Comment by jordon31** [comment]
https://github.com/jordon31/OF-SCR

try my updated script
