### ISSUE TITLE
skipping pictures and videos

### ISSUE THREAD

**Issue by YouthGarage** [k0rnh0li0/onlyfans-dl#85]
Someone else has the issue that certain amount of picture are skipped?

120p and 9v out of 605p and 10v from one model 

and

1028p  and 97v out of 1947p and 98v from another one

**Comment by drnick88101** [comment]
I noticed this same problem on a profile. It has 951 photos and 608 videos but the program only finds 500 photos and 600 videos

**Comment by bnsave100** [comment]
me too just tried 200 pics profile only 100 downloaded
