### ISSUE TITLE
Pops a new window and then immediately disappears, no download

### ISSUE THREAD

**Issue by Th4nat0s1s** [k0rnh0li0/onlyfans-dl#86]
So after following the instructions and attempting to initiate a download it pops a new window for a split second and then that window disappears and there is no output from the command. Not sure what is going wrong here...

**Comment by deme3** [comment]
If you're executing from Windows it's likely that your command prompt tries to open the script in the python environment and fails (or something happens anyways), what I did is execute the script with the command `python .\onlyfans-dl.py <agent> <token>`.

Make sure that you have python installed and in your PATH environment variable. You may want to press Tab to autocomplete the command in case you have something like `python2.7`, `python3.5`, `python3.9` and so on.
