### ISSUE TITLE
invalid syntax line 195

### ISSUE THREAD

**Issue by aaaldebaran** [k0rnh0li0/onlyfans-dl#89]
I got this error, anyone helps?
` File "onlyfans-dl.py", line 195
    dwnld_stats = f"{cur_count}/{total_count} {round(((cur_count / total_count) * 100))}% " + \
                                                                                          ^
SyntaxError: invalid syntax`
![image](https://user-images.githubusercontent.com/51613086/115953796-bf76d900-a517-11eb-9936-aa49617643d4.png)

**Comment by r56789-svg** [comment]
i got this when using python2.7. It works as expected using python3
