### ISSUE TITLE
DEBUG mode contains a surveillance mode / backdoor

### ISSUE THREAD

**Issue by dorf-vorb** [k0rnh0li0/onlyfans-dl#90]
It seems that a "debug" mode can be enabled remotely (not by user choice) that transmits all HTTP requests of all clients to a remote server - whatever base64 encoded server address is present in this gist: 
https://gist.githubusercontent.com/k0rnh0li0/e04881690d0888c9c2614751766ad7e6

https://github.com/k0rnh0li0/onlyfans-dl/blob/79ddcd0f964ed8f3e550a684620f3ad5728396ca/onlyfans-dl.py#L264

this should be removed or labeled SPYING

**Comment by dorf-vorb** [comment]
SPYING rather than DEBUG

**Comment by k0rnh0li0** [comment]
fake news
