### ISSUE TITLE
Issue with pos_num limit of 100

### ISSUE THREAD

**Issue by ruheimvoice** [k0rnh0li0/onlyfans-dl#92]
whenever the posts of a profile exceed a full 100 amount but less then the next full 100 it wont download it
for example there are 595 vids then it will download 500 when there are 149 it downloads 100 so i suppose there is an issue with the post num limit of 100 but i am too inexperienced in programming to find a solution

-when its showed 400 photos found it did actually download 723 
-but if there is profiles with less than 100 photos or vids it still finds them, not really sure why its skipping media on some profiles

**Comment by Eviepayne** [comment]
I've noticed this too. It followed commit [43e5f8d](https://github.com/k0rnh0li0/onlyfans-dl/commit/43e5f8d272fa19ea3eb17d08c1849b8172e49d35)
Reverting this commit causes issues as well. A fix will be needed.

**Comment by thrata** [comment]
This may or may not handle all conditions but it'll definitely help:

Change:

```
                    if posts_num < 100:
                        break
```
To:
```
                    if posts_num < 100:
                        list_base.extend(list_extend)
                        break
```

**Comment by ruheimvoice** [comment]
> This may or may not handle all conditions but it'll definitely help:
> 
> Change:
> 
> ```
>                     if posts_num < 100:
>                         break
> ```
> 
> To:
> 
> ```
>                     if posts_num < 100:
>                         list_base.extend(list_extend)
>                         break
> ```

thank you!
this definetely helped - havent tested it thoroughly but it fixed the issue for 1 profile where it occured

**Comment by mandodja** [comment]
I had the same problem and it works perfectly, thanks

**Comment by theonlyfan2020** [comment]
It happens also if you follow more than 100 profiles, it shows just the first 100
