### ISSUE TITLE
Im newbie with python 

### ISSUE THREAD

**Issue by kospix** [k0rnh0li0/onlyfans-dl#99]
HI i get this error: 

Getting user auth info...

ERROR: Application token is required.

**Comment by jahakatsotaanpa** [comment]
I'm even more newbie and of little help but today I got the program to run by manually changing the code to the new one
https://github.com/k0rnh0li0/onlyfans-dl/pull/98/files

Then follow the new instructions (also on the same page)

**Comment by kospix** [comment]
not found for me:
Getting target profile info...
x

ERROR: Please refresh the page

**Comment by kospix** [comment]
I closed Web browser, script found, thanks
